### ISSUE TITLE
Unable to create wikilink alias that only differs in case from page title

### ISSUE THREAD

**Issue by fnurl** [dendronhq/dendron#2575] opened 2022-03-15 21:09 UTC
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [x] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

If the alias used in a wikilink is the same as the page name, the page title is used. This makes it impossible to force the display text to be in lowercase.

## To Reproduce

1. Create a page with the name page and the page `page` with the title `Page`.
2. Create a new page and add the wikilink `[[page|page]]`

## Expected behavior

The link in the preview should be shown as `page`, not `Page`.

## Desktop (please complete the following information)

- OS: macOS
- Versions (all that apply to bug):
  - Dendron Extension: v0.85.0
  - VS Code version: 1.65.2

**Comment by kevinslin** [comment] 2022-03-17 22:08
thanks for the report, adding to backlog

**Comment by Harshita-mindfire** [comment] 2022-07-29 11:18
This seems like a duplicate of https://github.com/dendronhq/dendron/issues/1989. @fnurl Can we track this issue with the former one?

**Closed** 2022-08-01 12:12 UTC
Labels: type.bug, status.info-needed, scope.views
