### ISSUE TITLE
Support for arbitrary block references

### ISSUE THREAD

**Issue by awlego** [dendronhq/dendron#568] opened 2021-03-23 23:36 UTC
## Please Select if your Request is Either something new or an Enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [x] Hierarchy
- [ ] Graph
- [x] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

I'm frustrated when I want to reference a section of a note that isn't fully fleshed out with markdown blocks and have to go back and add markdown just so I can quote/embed part of my note elsewhere in my dendron vault.

## Describe the solution you'd like ##

Best case would be the ability to highlight any number of lines and press a hotkey and have a reference to those line generated and copied to my clipboard. Much like how today I can get a copy to a reference of a section onwards (`[[daily.journal.2021.02.08#start-quote,1:#*]]`), but for arbitrary lines.

## Describe alternatives you've considered ##

The block and note level references already exist, which are a kind of alternative I guess... A hotkey to autogenerate a specific markdown around a note that lets it easily be referenced in a reference quote might work, but that sounds messy.

## Additional context ##

Asked about on Discord and `kevins8#0590` said I should report here.

**Comment by andrey-jef** [comment] 2021-03-24 05:08
I vote for this feature too. 

Just for reference, I attached the link that depict the 'block reference ID' from Obsidian
https://help.obsidian.md/How+to/Link+to+blocks#Link+to+blocks

**Comment by aleksey-rowan** [comment] 2021-03-24 17:59
This is a duplicate of https://github.com/dendronhq/dendron/issues/560.

**Comment by kpathakota** [comment] 2021-03-24 20:11
Closed duplicate - adding 2 to the vote total for the linked issue.

**Closed** 2021-03-24 20:11 UTC
Labels: area.hierarchy, area.misc, status.triage-needed, type.feature
