### ISSUE TITLE
Note preview does not render spaces around links in headers

### ISSUE THREAD

**Issue by samuelxyz** [dendronhq/dendron#3396] opened 2022-08-13 04:35 UTC
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [x] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [x] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

When a link is inserted in the middle of a header, the Dendron markdown preview does not render any spaces around the link. For example,

### Header with a [link](https://dendron.so) in it

appears as

## To Reproduce

1. Inside a note, try to put a hyperlink (`[link](address)`) or note wikilink (`[[link]]`) inside a header, with other words before and/or after the link.
2. Open the markdown preview and observe how the header is rendered.

## Expected behavior

Spaces appear before and after the link in the header.

## Screenshots

Raw markdown:

<img width="331" alt="image" src="https://user-images.githubusercontent.com/41557313/184468502-71f0cf6a-9732-49f1-9a64-8a939214d694.png">

What the preview shows:

<img width="287" alt="image" src="https://user-images.githubusercontent.com/41557313/184468506-9dd5a1aa-7bc7-4f05-80c3-e9f42502768a.png">

## Desktop (please complete the following information)

OS: Windows 11 Home 10.0.22000
Browser (if with published websites; include version): N/A
Versions (all that apply to bug):
Dendron Extension: v0.107.2
VS Code version: 1.70.1
Dendron CLI:

## Dendron Log file

[dendron.log](https://github.com/dendronhq/dendron/files/9330836/dendron.log)

**Comment by hikchoi** [comment] 2022-08-16 03:33
Thank you for the report. I can reproduce this. We'll let you know when this gets resolved

**Comment by namjul** [comment] 2022-08-29 07:01
Reopening because #3403 did only apply the fix to the preview but not to publishing (`nextjs-template`)

**Comment by namjul** [comment] 2022-10-10 09:44
This has been fixed in https://github.com/dendronhq/dendron/pull/3525

**Closed by namjul** 2022-10-10 09:44 UTC
Labels: type.bug, scope.markdown, scope.views
