### ISSUE TITLE
Document Display Order in the Dendron Tree View

### ISSUE THREAD

**Issue by micharris42** [dendronhq/dendron#440] opened 2021-01-03 02:21 UTC
**Describe the bug**
In the Dendron Tree View, documents are displayed in order of creation, not by the document title or by the content of the frontmatter. This is especially noticeable for journal notes. If a set of journal notes are created out of chronological order, they will show up in the Dendron Tree View in the order of their creation, rather then ordered by date. Amending the "created" field in the frontmatter has no effect.

**To Reproduce**
1. Create a journal note.
2. Create a second journal note for an earlier date. 
3. The second note will be displayed below the first note, despite that it is for an earlier date in time.

**Expected behavior**
That documents be displayed in the Dendron Tree View ordered by either the document title or the content of the frontmatter, not by date of creation. If this is the intended behavior, that there be an option to sort the content of the Dendron Tree View.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/76890677/103470410-0d38bd00-4d40-11eb-9377-30bc9e5d346e.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: NA
 - Version: Dendron 0.22.0

**Additional context**
I apologize if this has already been addressed in an earlier issue. However, after going through the Dendron documentation and the issues already on GitHub, I was unable to find a solution. Any suggestions would be appreciated. Thank you.

**Comment by flammehawk** [comment] 2021-01-03 18:28
I think a setting for the sort order would be preferable. 

I personaly would like to have my notes sorted alphabetical.

But journal notes in a way that the journal entry for the newest day is displayed first. 

Which is opinionated others may want to have the inverse from what I want so I think a setting would be the best choice.

**Comment by kevinslin** [comment] 2021-01-04 18:30
Thanks for the issue and you're the first one to bring it up so we're good. Formally including this in our backlog

**Comment by aleksey-rowan** [comment] 2021-04-03 21:05
Many note-taking apps allow for manual sorting of notes/containers and often don't have functionality for auto-sorting. I would prefer my notes auto-sorted by metadata title with an option to manually adjust their positions if needed. There could be an additional metadata property (`sort-title` for example) to override the actual title for sorting purposes, like when sorting books or movies, so all books that start with "the" don't get grouped together.

**Comment by kevinslin** [comment] 2021-04-04 15:39
an update on the tree view. we're planning on creating a dedicated dendron panel using a custom webview to accommodate custom ordering as well as additional functionality (eg. drag and drop assets). this will most likely be an end of april to may item but in the meanwhile, we're going to create an index command to help people create index notes. See #603 for more details and please let me know if you have any suggestions :)

**Comment by af4jm** [comment] 2021-05-05 17:50
hmm, I haven't noticed journals sorting by creation, but I have seen all-numeric entries sorting alphabetically 
![image](https://user-images.githubusercontent.com/849948/117185538-ef3f9f80-ada7-11eb-8a2b-d2651847e5b1.png)

the other thing I could see making perfect sense is to use the nav_order field in front matter, if it exists

so it could either be a setting, or it could be nav_order for notes that have them, otherwise numeric if applicable, otherwise alpha

if you go the setting route, it could get wonky depending on where the setting goes... e.g. would there be a default in VSCode settings (or dendron.yml)? could you override it with a setting in the parent note's front matter?

or is my developer propeller-hat trying to turn a small problem with a simple solution into something much more complicated than it needs to be?

**Comment by micharris42** [comment] 2021-05-06 02:18
Small update to this issue, as it has gotten bumped today:

I recently did a bit of experimenting with Dendron that did not pan out, and it was easier just to replace my vault with an earlier backup. 

Upon reopening my Dendron workspace, I found the Tree View was now sorted alphanumerically, with the exception that existing hierarchical notes were placed above the non-existent notes (the placeholders marked with +). This was the first time I had replaced my vault in such a fashion, so I can not determine whether this is new behavior.

My takeaway, is that I now have no idea how Dendron chooses to organize the hierarchy in the Tree View. It seems to use alphanumeric ... except for when it chooses not to. 

Not sure how helpful this is to include, but this is how my user experience with the Tree View has gone.

**Comment by kevinslin** [comment] 2021-05-06 14:18
Thanks for the update. The tree view is alphanumeric by default by the
recent caching updates means that updated notes can appear out of order in
the tree view because of how that's being initialized. we have a fix coming
for this!

**Comment by Bassmann** [comment] 2021-08-15 18:42
Is there any update on the sort order topic? For me the treeview still shows a random unsorted order and I _really_ look forward to finding my notes in the treeview. As it is now it seems somewhat useless (at least for my workflow).

**Comment by kevinslin** [comment] 2021-09-22 14:18
Hey @Bassmann can you let us know if this is still an issue for you? If so, do you have a screenshot of what the out of order tree view looks like?

**Comment by Bassmann** [comment] 2021-09-22 16:15
I think it was still the same issue last time I checked. I'll check next week once I'm back at my laptop

Am 22. September 2021 16:19:00 MESZ schrieb Kevin Lin ***@***.***>:

**Comment by hrmnjt** [comment] 2021-12-02 22:27
Hi team. As I'm checking now, `nav_order` affects the publishing order but not the index in tree view. Is this intended behavior? It would make sense for me to use `nav_order` in tree view index as well!

**Comment by SeriousBug** [comment] 2021-12-29 10:14
Hi. I believe this issue has been fixed with the latest Dendron, the tree now follows alphanumeric order. Please let us know if you still experience this issue, otherwise it will close in a few days.

**Comment by Bassmann** [comment] 2021-12-29 14:48
For my needs it works indeed already quite some time. Sorry for not responding

**Closed** 2021-12-29 18:44 UTC
Labels: type.enhancement, area.workbench, size.mid, status.info-needed
