### ISSUE TITLE
Paste Image (Ctrl + Alt + V) shows "There is not an image in the clipboard"

### ISSUE THREAD

**Issue by eunchan** [dendronhq/dendron#311] opened 2020-10-28 05:28 UTC
**Describe the bug**
After clip the image (copy image on web browser or Win + Shift + S then select the part of the screen or snip it program to capture the screen), Paste image with the plug in shows the confirmation box then the error "There is not an image in the clipboard" is shown.

**To Reproduce**
1. on Windows 10, press Win + Shift + S
2. drag to copy the screen into clipboard
3. In the markdown, press Ctrl + Alt + V to paste image

**Expected behavior**
Expect the image is created under `assets/images` directory and add the link in the markdown file

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Doesn't matter
 - Version: VSCode 1.50.1

**Additional context**

**Comment by seedublancaster** [comment] 2020-10-28 17:59
Not to go with the classic Level 1 Help Desk super obvious answer, but just to double check: are you able to paste the image from the clipboard into another application that accepts images (e.g. paint)?  Without being able to reproduce it directly myself (I am on Mac and cannot install VSCode on the only Windows 10 I have access to at the moment), that error message sounds like the VSCode keybind and extension are working just not finding an image in the clipboard to paste.

If you are able to paste from that same source into another image application, perhaps windows is presenting the image data in a different format... can you try the following: open paint (or another image program) and pasting or draw an image.  Next, select and copy the image, then try using the keybinding in vscode to paste that image.

The only other last troubleshooting idea I have is to verify that you have the same result using this extension but outside of Dendron.  Open or create a different (non-Dendron) workspace or file and attempt the same process(es) above.

In any event, it *sounds* (so far) more like an issue with your setup and or the paste-image extension than with Dendron.
A quick browse of open issues on the GH of the extension shows a couple of similar sounding issues, but perhaps you can either add to one of those or open a new one if it turns out to be a bug with the extension:
https://github.com/mushanshitiancai/vscode-paste-image/issues

**Comment by eunchan** [comment] 2020-10-28 18:27
Thanks for the reply. I was able to paste the image to other tools without issue. I forgot to describe above that I am using VSCode on WSL. I think this is the reason. I can use that feature on macOS too. Let me dig the link you've shared.

**Comment by eunchan** [comment] 2020-10-28 18:32
Looks like this extension let me proceed one more step. https://marketplace.visualstudio.com/items?itemName=sakamoto66.vscode-paste-image

It, now does not show the error message but successfully add the link to the markdown file. However, it does not create the image file on WSL.

**Comment by seedublancaster** [comment] 2020-10-28 19:55
Hmm, meaning that you are running Windows 10 natively, have WSL setup and you are running a Linux Distribution on-top of Win 10 and running VSCode inside that environment?  Out of curiosity, is there a reason you have to run VSCode inside of WSL instead of natively in Win 10?  I am wondering if you can run VSCode with Dendron natively in Win 10.

**Comment by eunchan** [comment] 2020-10-28 19:58
I agree. After seeing this, I think it is worth to run dendron repo inside Windows 10. I was using WSL to make the environment similar to the macOS and also linux (workstation) and share dendron on every systems. 

Let me try on Windows 10 . Thanks for help.

**Comment by seedublancaster** [comment] 2020-10-28 20:03
Did not mean to come across as dismissive... In some quick searching, I did come across "x410", which seems to claim to allow seamless image transfer via clipboard between Windows and WSL.  Heavily caveated: I have never used WSL myself nor x410, and cannot vouch for it at all!  It turned up in one of my google searches.

**Comment by kevinslin** [comment] 2020-10-29 14:55
Checking in on this issue. @eunchan did you end up getting this resolved?

**Comment by kevinslin** [comment] 2020-11-19 03:51
closing this issue. feel free to re-open if it comes up

**Closed by kevinslin** 2020-11-19 03:51 UTC
Labels: status.pending
