### ISSUE TITLE
Tree view isn't sorted

### ISSUE THREAD

**Issue by Bassmann** [dendronhq/dendron#601] opened 2021-04-03 14:24 UTC
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [x] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [ ] Hierarchy
- [ ] Graph
- [ ] Misc (Choose this if your not sure)

## Describe the bug

The tree view shows hierarchies in a random order

## To Reproduce

1. Go to 'Dendron Tree View'
2. Open a vault
3. See error

## Expected behavior

I'd expect the tree view to sort the hierarchies alphabetical in ascending order.

## Screenshots

![grafik](https://user-images.githubusercontent.com/3171330/113481260-c9696700-9498-11eb-88f1-21ed606d3478.png)

## Desktop (please complete the following information)

- OS: Windows
- Dendron Version 0.35.1
- VSCode Version 1.55.0

**Comment by micharris42** [comment] 2021-04-03 15:05
This is a duplicate of #440.

**Comment by kevinslin** [comment] 2021-04-04 15:38
an update on the tree view. we're planning on creating a dedicated dendron panel using a custom webview to accommodate custom ordering as well as additional functionality (eg. drag and drop assets). this will most likely be an end of april to may item but in the meanwhile, we're going to create an index command to help people create `index` notes. See https://github.com/dendronhq/dendron/issues/603 for more details and please let me know if you have any suggestions :)

**Comment by kevinslin** [comment] 2021-04-04 15:39
closing this so we can track it in #440

**Closed by kevinslin** 2021-04-04 15:39 UTC
Labels: area.ui, status.triage-needed, type.bug
