### ISSUE TITLE
Insert Note Link throws an unhandled error

### ISSUE THREAD

**Issue by fdaguin** [dendronhq/dendron#1172] opened 2021-08-19 10:40 UTC
## Please select the area your Bug applys to.

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

The `Insert Note Link` throws `unhandled error: [object Object]`.

## To Reproduce

1. Open a note
2. Use the `Insert Note Link` command
3. Pick a note from the `Insert Note Link` results

## Expected behavior

No error is thrown.

## Screenshots

![image](https://user-images.githubusercontent.com/72013963/130048659-7bc3172b-68a3-4404-9035-0edf45ec69db.png)

## Desktop

I'm using Dendron on [code-server](https://github.com/cdr/code-server), with the following environment:

- OS: Ubuntu 20.04
- code-server: v3.11.0 (VS Code: v1.57.1)
- Dendron: 0.55.1

I'm accessing Dendron with the following environment:

- OS: Windows 10
- Browser: Google Chrome

## Dendron Log file

Please attach the output of `>Dev:Dendron: Open Logs` here

```json
{"level":30,"time":1629366421973,"pid":1937874,"hostname":"ide","name":"dendron","ctx":"Logger:configure","msg":"exit","logLevel":"info"}
// I removed the `_activate` entry here.
{"level":30,"time":1629366422257,"pid":1937874,"hostname":"ide","name":"dendron","ctx":"DendronWorkspace","msg":"initialized"}
{"level":30,"time":1629366422322,"pid":1937874,"hostname":"ide","name":"SegmentClient","msg":"user telemetry setting: enabled by migration"}
{"level":30,"time":1629366422322,"pid":1937874,"hostname":"ide","name":"SegmentClient","msg":"telemetry initializing"}
{"level":30,"time":1629366422322,"pid":1937874,"hostname":"ide","name":"SegmentClient","msg":"using existing id"}
{"level":30,"time":1629366422323,"pid":1937874,"hostname":"ide","name":"dendron","msg":"Telemetry is disabled? false"}
{"level":30,"time":1629366422326,"pid":1937874,"hostname":"ide","name":"dendron","ctx":"_activate","config":{"version":1,"vaults":[{"fsPath":"vault"}],"useFMTitle":true,"useNoteTitleForLink":true,"noAutoCreateOnDefinition":true,"noLegacyNoteRef":true,"noXVaultWikiLink":true,"lookupConfirmVaultOnCreate":false,"mermaid":true,"useKatex":true,"autoFoldFrontmatter":false,"dev":{"enableWebUI":true,"enableLinkCandidates":true,"enablePreviewV2":true},"lookup":{"note":{"selectionType":"selectionExtract"}},"journal":{"dailyDomain":"daily","name":"journal","dateFormat":"y.MM.dd","addBehavior":"childOfDomain","firstDayOfWeek":1},"scratch":{"name":"scratch","dateFormat":"y.MM.dd.HHmmss","addBehavior":"asOwnDomain"},"site":{"copyAssets":true,"siteHierarchies":["root"],"siteRootDir":"docs","usePrettyRefs":true,"duplicateNoteBehavior":{"action":"useVault","payload":["aws","vault"]}},"noTelemetry":false,"noCaching":false,"insertNoteIndex":{"marker":true},"initializeRemoteVaults":true,"dendronVersion":"0.52.0"},"configMigrated":false,"msg":"read dendron config"}
{"level":30,"time":1629366422334,"pid":1937874,"hostname":"ide","name":"dendron","ctx":"_activate","installStatus":"NO_CHANGE","currentVersion":"0.55.1","previousWorkspaceVersion":"0.55.1","previousGlobalVersion":"0.55.1","platform":"linux","extensions":[{"id":"dendron.dendron-paste-image"},{"id":"dendron.dendron-markdown-shortcuts"},{"id":"redhat.vscode-yaml","version":"0.22.0","active":false},{"id":"dendron.dendron-markdown-preview-enhanced","version":"0.10.45","active":false}],"vaults":[{"fsPath":"vault"}]}
{"level":30,"time":1629366422338,"pid":1937874,"hostname":"ide","name":"execServer","state":"enter"}
{"level":30,"time":1629366422350,"pid":1937874,"hostname":"ide","name":"execServer","state":"post:exec.node"}
{"level":30,"time":1629366423351,"pid":1937874,"hostname":"ide","name":"execServer","state":"message","message":"33829"}
{"level":30,"time":1629366423351,"pid":1937874,"hostname":"ide","name":"dendron","ctx":"WSUtils.handleServerProcess","msg":"subprocess running","pid":1937888}
{"level":30,"time":1629366423352,"pid":1937874,"hostname":"ide","name":"dendron","ctx":"_activate","msg":"post-start-server","port":33829,"durationStartServer":1094}
// I removed the `FileStorageV2` entry here.
{"level":30,"time":1629366423356,"pid":1937874,"hostname":"ide","name":"dendron","ctx":"dendron.reloadIndex:run","msg":"pre-execute"}
{"level":30,"time":1629366423356,"pid":1937874,"hostname":"ide","name":"dendron","ctx":"ReloadIndex.execute","msg":"enter"}
// I removed the `parseSchemaModuleOpts` entries here.
{"level":30,"time":1629366430091,"pid":1937874,"hostname":"ide","name":"dendron","ctx":"ReloadIndex.execute","durationEngineInit":6711}
{"level":30,"time":1629366430092,"pid":1937874,"hostname":"ide","name":"dendron","ctx":"ReloadIndex.execute","msg":"exit"}
{"level":30,"time":1629366430092,"pid":1937874,"hostname":"ide","name":"dendron","ctx":"dendron.reloadIndex:run","msg":"post-execute"}
{"level":30,"time":1629366430096,"pid":1937874,"hostname":"ide","name":"dendron","ctx":"reloadWorkspace","msg":"post-ws.reloadWorkspace"}
{"level":30,"time":1629366430096,"pid":1937874,"hostname":"ide","name":"dendron","ctx":"reloadWorkspace","msg":"exit"}
{"level":30,"time":1629366430097,"pid":1937874,"hostname":"ide","name":"dendron","ctx":"postReloadWorkspace","msg":"same wsVersion"}
{"level":30,"time":1629366430097,"pid":1937874,"hostname":"ide","name":"dendron","ctx":"postReloadWorkspace","msg":"exit"}
{"level":30,"time":1629366430099,"pid":1937874,"hostname":"ide","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree"}
{"level":30,"time":1629366430463,"pid":1937874,"hostname":"ide","name":"dendron","ctx":"setupViews","msg":"init:treeViewV2"}
{"level":30,"time":1629366430465,"pid":1937874,"hostname":"ide","name":"dendron","ctx":"setupViews","msg":"initWebUI"}
{"level":30,"time":1629366430465,"pid":1937874,"hostname":"ide","name":"dendron","ctx":"setupViews","msg":"init:backlinks"}
{"level":30,"time":1629366430473,"pid":1937874,"hostname":"ide","name":"dendron","ctx":"activateWorkspace","stage":"prod","msg":"enter"}
{"level":30,"time":1629366430477,"pid":1937874,"hostname":"ide","name":"dendron","ctx":"toggleViews","msg":"views enabled: true"}
{"level":30,"time":1629366430477,"pid":1937874,"hostname":"ide","name":"dendron","ctx":"_activate","msg":"fin startClient","durationReloadWorkspace":8212}
{"level":30,"time":1629366430477,"pid":1937874,"hostname":"ide","name":"dendron","ctx":"showWelcomeOrWhatsNew","version":"0.55.1","previousExtensionVersion":"0.55.1"}
{"level":30,"time":1629366432451,"pid":1937874,"hostname":"ide","name":"dendron","ctx":"LookupControllerV3:new","msg":"enter"}
{"level":30,"time":1629366432452,"pid":1937874,"hostname":"ide","name":"dendron","ctx":"prepareQuickPick","msg":"enter"}
{"level":30,"time":1629366432454,"pid":1937874,"hostname":"ide","name":"dendron","ctx":"prepareQuickPick","msg":"exit"}
{"level":30,"time":1629366432454,"pid":1937874,"hostname":"ide","name":"dendron","ctx":"showQuickPick","msg":"enter"}
{"level":30,"time":1629366432455,"pid":1937874,"hostname":"ide","name":"dendron","ctx":"showQuickPick","msg":"onUpdatePickerItems:pre"}
{"level":30,"time":1629366432455,"pid":1937874,"hostname":"ide","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"","justActivated":true}
{"level":30,"time":1629366432457,"pid":1937874,"hostname":"ide","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"","profile":1,"cancelled":false}
{"level":30,"time":1629366432457,"pid":1937874,"hostname":"ide","name":"dendron","ctx":"showQuickPick","msg":"onUpdatePickerItems:post"}
{"level":30,"time":1629366432458,"pid":1937874,"hostname":"ide","name":"dendron","ctx":"NoteLookupProvider.provide","msg":"enter"}
{"level":30,"time":1629366432459,"pid":1937874,"hostname":"ide","name":"dendron","ctx":"NoteLookupProvider.provide","msg":"exit"}
{"level":30,"time":1629366432459,"pid":1937874,"hostname":"ide","name":"dendron","ctx":"showQuickPick","msg":"exit"}
{"level":50,"time":1629366436704,"pid":1937874,"hostname":"ide","name":"dendron","msg":"unhandled error: [object Object]"}
```

**Comment by hikchoi** [comment] 2021-08-20 04:08
Thank you for the report.
This seems to be a regression on our end. Apologies 🙏🏼 
I have also personally ran into this issue locally, so this doesn't seem to be a code-server specific issue. 
I will investigate this and let you know when the fix is being shipped.

**Comment by kevinslin** [comment] 2021-08-24 22:08
this should be fixed in v56 of Dendron. please post here if not, otherwise this issue will auto close in 3 days

**Comment by fdaguin** [comment] 2021-08-24 22:19
After some tests with this new release, I'm not able to reproduce this issue. Thanks for the fix @hikchoi !

**Closed** 2021-08-31 20:44 UTC
Labels: type.bug, area.create
