### ISSUE TITLE
Correct vault is not selected when creating note with lookup autocomplete

### ISSUE THREAD

**Issue by fnurl** [dendronhq/dendron#2617] opened 2022-03-23 13:44 UTC
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [x] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

After choosing `vault1`, the note is created in `vault2`.

## To Reproduce

1. Trigger lookup.
2. Auto-complete to parent note title.
3. Add child name.
4. Select "Create New" in dropdown
5. Press enter.
6. Select vault.

## Expected behavior

New note is created in selected vault.

## Screenshots

https://user-images.githubusercontent.com/106794/159713299-405c86f2-f857-4c6b-82f8-3264ed386dcf.mp4

## Desktop (please complete the following information)

- OS: macOS 12.1
- Browser (if with published websites; include version): [e.g. chrome, safari]
- Versions (all that apply to bug):
  - Dendron Extension: 0.86.1
  - VS Code version: 1.65.2
  - Dendron CLI: N/A

## Additional context

Here is a zip-file with the workspace from the video: [test1.zip](https://github.com/dendronhq/dendron/files/8333487/test1.zip)

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` here

**Comment by SeriousBug** [comment] 2022-03-23 20:34
Thanks for reporting this bug! This seems to be a bug with the autocomplete, could you try without autocomplete (without pressing tab)?

We'll work on a fix in the meantime.

**Comment by kevinslin** [comment] 2022-03-23 22:17
We root caused the issue and have a fix ready. Will be shipped as part of next week's release

**Comment by kevinslin** [comment] 2022-03-23 22:18
FYI - for anyone interested, I did a pairing session with another team mate to diagnose this bug. You can see the session here: https://www.loom.com/share/99cdf1057d0247bf97b8355902850167

**Comment by kevinslin** [comment] 2022-03-30 14:10
This should be fixed in v88 of Dendron. please post here if not, otherwise this issue will auto close in 3 days.

**Closed** 2022-04-02 14:24 UTC
Labels: type.bug, status.info-needed, scope.lookup
