### ISSUE TITLE
custom styling not working

### ISSUE THREAD

**Issue by lcpichette** [dendronhq/dendron#3992] opened 2024-09-09 22:15 UTC
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [x] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Using `custom.css` via `dendron.yml` -> `preview.theme` -> `custom` changing the background color, as referenced in the official docs [applying a custom theme](https://wiki.dendron.so/notes/0fbg5vbv5jzb0623pbi4v3t/#applying-a-custom-theme), doesn't change the background color.

## To Reproduce

1. Go to dendron.yml
2. Change preview.theme to custom
3. Preview journal note

## Expected behavior

Background color should change to use the one specified in custom.css

## Screenshots

https://github.com/user-attachments/assets/666ff0e6-ed61-4813-bd59-252fafb5bbb3

## Desktop (please complete the following information)

- OS: MacOS 15
- Browser (if with published websites; include version): [e.g. chrome, safari] N/A
- Versions (all that apply to bug):
  - Dendron Extension: Latest version
  - VS Code version: 1.91.1
  - Dendron CLI: N/A

## Dendron Log file

[dendron.log](https://github.com/user-attachments/files/16937165/dendron.log)

**Comment by Serrindipity** [comment] 2024-09-23 18:45
Duplicate of #3988

**Comment by lcpichette** [comment] 2024-09-23 23:26
Closed as it's a duplicate

**Closed** 2024-09-23 23:25 UTC
Labels: type.bug, status.triage-needed, scope.views
