### ISSUE TITLE
Show preview has a light mode

### ISSUE THREAD

**Issue by Saadchr** [dendronhq/dendron#2663] opened 2022-03-31 11:19 UTC
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [x] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [X] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

My preview page has now a light theme  while it was always turned on dark mode. 
I attributed to all the theme settings the dark mode (VS CODE, and settings of dendron extension)but the note preview is still in Light mode

## Expected behavior

A dark mode

## Screenshots

<img width="1163" alt="CleanShot 2022-03-31 at 11 19 03@2x" src="https://user-images.githubusercontent.com/74289775/161043574-6eed8ffd-07e3-4f6d-b027-09c73ea5819a.png">

## Desktop (please complete the following information)

- OS: MAC OS

- Versions (all that apply to bug):
  - Dendron Extension: v 0.88.0
  - VS Code version: 1.66.0 
  - Dendron CLI:

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` here

{"level":30,"time":1648724787345,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"Logger:configure","msg":"exit","logLevel":"info"}
{"level":30,"time":1648724787403,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"_activate","stage":"prod","isDebug":false,"logLevel":"info","logPath":"/Users/saadchraibi/Library/Application Support/Code/logs/20220331T080524/exthost5/dendron.dendron","extensionPath":"/Users/saadchraibi/.vscode/extensions/dendron.dendron-0.88.0","extensionUri":"/Users/saadchraibi/.vscode/extensions/dendron.dendron-0.88.0","workspaceFile":"/Users/saadchraibi/Saad Dendron/dendron.code-workspace","workspaceFolders":["/Users/saadchraibi/Saad Dendron/vault","/Users/saadchraibi/SCRIMBA/Javascript for free/generate-imgs","/Users/saadchraibi/SCRIMBA/Javascript for free/Chrome extension- Projet réalisé from scratch","/Users/saadchraibi/SCRIMBA/Front end career path/Module 4 Javascript Css Fundamentals/CSS fundamentals Challenges","/Users/saadchraibi/SCRIMBA/Front end career path/Module 4 Javascript Css Fundamentals/Javascript Challenges","/Users/saadchraibi/SCRIMBA","/Users/saadchraibi/livres-programmation","/Users/saadchraibi/Datacamp"]}
{"level":30,"time":1648724787403,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"SegmentClient","msg":"No cache path for Segment specified. Failed event uploads will not be retried."}
{"level":30,"time":1648724787404,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"SegmentClient","msg":"user telemetry setting: enabled by config"}
{"level":30,"time":1648724787404,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"SegmentClient","msg":"telemetry initializing"}
{"level":30,"time":1648724787404,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"SegmentClient","msg":"using existing id"}
{"level":30,"time":1648724787407,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"DendronExtension","msg":"initialized"}
{"level":30,"time":1648724787412,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"_activate","msg":"initializeWorkspace","wsType":"CODE","currentVersion":"0.88.0","previousWorkspaceVersion":"0.88.0","previousGlobalVersion":"0.88.0","extensionInstallStatus":"NO_CHANGE"}
{"level":30,"time":1648724787417,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"SegmentClient","msg":"user telemetry setting: enabled by config"}
{"level":30,"time":1648724787417,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"SegmentClient","msg":"telemetry initializing"}
{"level":30,"time":1648724787417,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"SegmentClient","msg":"using existing id"}
{"level":30,"time":1648724787417,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","msg":"Telemetry is disabled? false"}
{"level":30,"time":1648724787417,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","msg":"Segment Residual Cache Path is at /Users/saadchraibi/Library/Application Support/Code/User/globalStorage/dendron.dendron/segmentresidualcache.log"}
{"level":30,"time":1648724787417,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"SegmentClient","msg":"Attempting to flush residual segment data from file."}
{"level":30,"time":1648724787420,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"_activate","workspaceInstallStatus":"NO_CHANGE","currentVersion":"0.88.0","previousWorkspaceVersion":"0.88.0","previousGlobalVersion":"0.88.0","platform":"darwin","extensions":[{"id":"dendron.dendron-paste-image"},{"id":"dendron.dendron-markdown-shortcuts","version":"0.12.1","active":true},{"id":"redhat.vscode-yaml","version":"1.6.0","active":false}],"vaults":[{"fsPath":"vault"}]}
{"level":30,"time":1648724787421,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"execServer","state":"enter"}
{"level":30,"time":1648724787422,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"execServer","state":"post:exec.node"}
{"level":30,"time":1648724787446,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","msg":"Segment Residual Cache flush attempted. {\"successCount\":0,\"nonRetryableErrorCount\":0,\"retryableErrorCount\":0}"}
{"level":30,"time":1648724787800,"pid":37946,"hostname":"MacBook-Pro-de-Saad.local","name":"SegmentClient","msg":"No cache path for Segment specified. Failed event uploads will not be retried."}
{"level":30,"time":1648724787800,"pid":37946,"hostname":"MacBook-Pro-de-Saad.local","name":"SegmentClient","msg":"user telemetry setting: enabled by config"}
{"level":30,"time":1648724787800,"pid":37946,"hostname":"MacBook-Pro-de-Saad.local","name":"SegmentClient","msg":"telemetry initializing"}
{"level":30,"time":1648724787800,"pid":37946,"hostname":"MacBook-Pro-de-Saad.local","name":"SegmentClient","msg":"using existing id"}
{"level":30,"time":1648724787810,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"execServer","state":"message","message":"50010"}
{"level":30,"time":1648724787810,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WSUtils.handleServerProcess","msg":"subprocess running","pid":37946}
{"level":30,"time":1648724787810,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"startServerProcess","msg":"post-start-server","port":50010,"durationStartServer":397}
{"level":30,"time":1648724787812,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree: enter"}
{"level":30,"time":1648724787812,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree: exit"}
{"level":30,"time":1648724787940,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"dendron.reloadIndex:run","msg":"pre-execute"}
{"level":30,"time":1648724787940,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"ReloadIndex.execute","msg":"enter"}
{"level":30,"time":1648724788045,"pid":37946,"hostname":"MacBook-Pro-de-Saad.local","name":"logger","ctx":"parsingSchemas","fname":"root","root":{"fsPath":"vault"},"imports":[]}
{"level":30,"time":1648724788145,"pid":37946,"hostname":"MacBook-Pro-de-Saad.local","name":"LinkUtils.getLinks","ctx":"getLinks","dlinksLength":1,"noteRefsLength":0,"wikiLinksLength":1}
{"level":30,"time":1648724788159,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"ReloadIndex.execute","durationEngineInit":134}
{"level":30,"time":1648724788159,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"ReloadIndex.execute","msg":"exit"}
{"level":30,"time":1648724788159,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"dendron.reloadIndex:run","msg":"post-execute"}
{"level":30,"time":1648724788161,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"reloadWorkspace","msg":"post-ws.reloadWorkspace"}
{"level":30,"time":1648724788161,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"reloadWorkspace","msg":"exit"}
{"level":30,"time":1648724788161,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"postReloadWorkspace","msg":"same wsVersion"}
{"level":30,"time":1648724788161,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"postReloadWorkspace","msg":"exit"}
{"level":30,"time":1648724788161,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"setupViews","msg":"init:treeViewV2"}
{"level":30,"time":1648724788162,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"setupBacklinkTreeView","msg":"init:backlinks"}
{"level":30,"time":1648724788165,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"activateWorkspace","stage":"prod","msg":"enter"}
{"level":30,"time":1648724788167,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"togglePluginActiveContext","state":"togglePluginActiveContext: true"}
{"level":30,"time":1648724788167,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"_activate","msg":"fin startClient","durationReloadWorkspace":750}
{"level":30,"time":1648724788167,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"showWelcomeOrWhatsNew","version":"0.88.0","previousExtensionVersion":"0.88.0"}
{"level":30,"time":1648724788202,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree: enter"}
{"level":30,"time":1648724788203,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree: exit"}
{"level":30,"time":1648724788228,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":0,"diagnosticsLength":0}}
{"level":30,"time":1648724792782,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"dendron.showPreview:run","msg":"pre-execute"}
{"level":30,"time":1648724792804,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"dendron.showPreview:run","msg":"post-execute"}
{"level":30,"time":1648724800680,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1648724800681,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"undefined"}
{"level":30,"time":1648724818020,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/Users/saadchraibi/Library/Application Support/Code/User/settings.json","reason":"Manual","msg":"enter"}
{"level":30,"time":1648724835984,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/Users/saadchraibi/Library/Application Support/Code/User/settings.json","reason":"Manual","msg":"enter"}
{"level":30,"time":1648724836955,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1648724836955,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"/Users/saadchraibi/Saad Dendron/vault/tutorials.scrimba.front-end-developer-career-path.mod-6-Next-Javascript.Build-a-RPG-part-1-the-setup.md"}
{"level":30,"time":1648724837020,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":0,"diagnosticsLength":0}}
{"level":30,"time":1648724838169,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1648724838169,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"undefined"}
{"level":30,"time":1648724841259,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1648724841260,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"/Users/saadchraibi/Saad Dendron/vault/tutorials.scrimba.front-end-developer-career-path.mod-6-Next-Javascript.Build-a-RPG-part-1-the-setup.md"}
{"level":30,"time":1648724841319,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":0,"diagnosticsLength":0}}
{"level":30,"time":1648724857808,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":[]}
{"level":30,"time":1648724857809,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1648724857809,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"undefined"}
{"level":30,"time":1648724971202,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["/Users/saadchraibi/Saad Dendron/vault/tutorials.scrimba.front-end-developer-career-path.mod-6-Next-Javascript.Build-a-RPG-part-1-the-setup.md"]}
{"level":30,"time":1648724971204,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1648724971205,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"/Users/saadchraibi/Saad Dendron/vault/tutorials.scrimba.front-end-developer-career-path.mod-6-Next-Javascript.Build-a-RPG-part-1-the-setup.md"}
{"level":30,"time":1648724971271,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":0,"diagnosticsLength":0}}
{"level":30,"time":1648724973635,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"dendron.showPreview:run","msg":"pre-execute"}
{"level":30,"time":1648724973638,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"dendron.showPreview:run","msg":"post-execute"}
{"level":30,"time":1648724973674,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1648724973675,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"undefined"}
{"level":30,"time":1648724980448,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1648724980449,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"/Users/saadchraibi/Saad Dendron/vault/tutorials.scrimba.front-end-developer-career-path.mod-6-Next-Javascript.Build-a-RPG-part-1-the-setup.md"}
{"level":30,"time":1648724980508,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":0,"diagnosticsLength":0}}
{"level":30,"time":1648724982482,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":0,"diagnosticsLength":0}}
{"level":30,"time":1648724982888,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":0,"diagnosticsLength":0}}
{"level":30,"time":1648724993719,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":[]}
{"level":30,"time":1648724993719,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1648724993719,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"undefined"}
{"level":30,"time":1648725020457,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/Users/saadchraibi/Library/Application Support/Code/User/settings.json","reason":"Manual","msg":"enter"}
{"level":30,"time":1648725036143,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/Users/saadchraibi/Library/Application Support/Code/User/settings.json","reason":"Manual","msg":"enter"}
{"level":30,"time":1648725036230,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/Users/saadchraibi/Library/Application Support/Code/User/settings.json","reason":"Manual","msg":"enter"}
{"level":30,"time":1648725039319,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/Users/saadchraibi/Library/Application Support/Code/User/settings.json","reason":"Manual","msg":"enter"}
{"level":30,"time":1648725039397,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/Users/saadchraibi/Library/Application Support/Code/User/settings.json","reason":"Manual","msg":"enter"}
{"level":30,"time":1648725040226,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/Users/saadchraibi/Library/Application Support/Code/User/settings.json","reason":"Manual","msg":"enter"}
{"level":30,"time":1648725040294,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/Users/saadchraibi/Library/Application Support/Code/User/settings.json","reason":"Manual","msg":"enter"}
{"level":30,"time":1648725042351,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/Users/saadchraibi/Library/Application Support/Code/User/settings.json","reason":"Manual","msg":"enter"}
{"level":30,"time":1648725042430,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/Users/saadchraibi/Library/Application Support/Code/User/settings.json","reason":"Manual","msg":"enter"}
{"level":30,"time":1648725050383,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/Users/saadchraibi/Library/Application Support/Code/User/settings.json","reason":"Manual","msg":"enter"}
{"level":30,"time":1648725051438,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/Users/saadchraibi/Library/Application Support/Code/User/settings.json","reason":"Manual","msg":"enter"}
{"level":30,"time":1648725073110,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/Users/saadchraibi/Library/Application Support/Code/User/settings.json","reason":"Manual","msg":"enter"}
{"level":30,"time":1648725078435,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/Users/saadchraibi/Library/Application Support/Code/User/settings.json","reason":"Manual","msg":"enter"}
{"level":30,"time":1648725081427,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/Users/saadchraibi/Library/Application Support/Code/User/settings.json","reason":"Manual","msg":"enter"}
{"level":30,"time":1648725182320,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["/Users/saadchraibi/SCRIMBA/Front end career path/Module 6 - Next javascript/index.html"]}
{"level":30,"time":1648725182337,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1648725182338,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WorkspaceWatcher:onFirstOpen","msg":"enter","fname":"index.html"}
{"level":30,"time":1648725186259,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"dendron.showPreview:run","msg":"pre-execute"}
{"level":30,"time":1648725186260,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"dendron.showPreview:run","msg":"post-execute"}
{"level":30,"time":1648725196099,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"dendron.showPreview:run","msg":"pre-execute"}
{"level":30,"time":1648725196105,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"dendron.showPreview:run","msg":"post-execute"}
{"level":30,"time":1648725200437,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":[]}
{"level":30,"time":1648725200437,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1648725200437,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"undefined"}
{"level":30,"time":1648725200438,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["/Users/saadchraibi/Saad Dendron/vault/tutorials.scrimba.front-end-developer-career-path.mod-6-Next-Javascript.Build-a-RPG-part-1-the-setup.md"]}
{"level":30,"time":1648725200439,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1648725200439,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"/Users/saadchraibi/Saad Dendron/vault/tutorials.scrimba.front-end-developer-career-path.mod-6-Next-Javascript.Build-a-RPG-part-1-the-setup.md"}
{"level":30,"time":1648725200510,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":0,"diagnosticsLength":0}}
{"level":30,"time":1648725593507,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"pre-execute"}
{"level":30,"time":1648725593509,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"execute","opts":{}}
{"level":30,"time":1648725593521,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"post-execute"}
{"level":30,"time":1648725593600,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":[]}
{"level":30,"time":1648725593600,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1648725593600,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"undefined"}
{"level":30,"time":1648725593601,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["/Users/saadchraibi/Library/Application Support/Code/logs/20220331T080524/exthost5/dendron.dendron/dendron.log"]}
{"level":30,"time":1648725593601,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1648725593602,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WorkspaceWatcher:onFirstOpen","msg":"enter","fname":"dendron.log"}
{"level":30,"time":1648725666347,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":[]}
{"level":30,"time":1648725666348,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1648725666348,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"undefined"}
{"level":30,"time":1648725709481,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"pre-execute"}
{"level":30,"time":1648725709482,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"execute","opts":{}}
{"level":30,"time":1648725709483,"pid":37937,"hostname":"MacBook-Pro-de-Saad.local","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"post-execute"}

**Comment by hikchoi** [comment] 2022-03-31 15:49
Thanks for creating the issue. We had a chat in Discord. 

Since this is resolved by reverting the VSCode version, I'll mark this to automatically close in 4 days.

**Comment by Airradda** [comment] 2022-04-01 01:51
This appears to be caused by the new [Reduced Motion Mode](https://code.visualstudio.com/updates/v1_66#_reduce-motion-mode) and the CSS that it causes to be inherited. This can be fixed for the user, at least by my testing, by simply turning `workbench.reduceMotion` from `auto` to `off`. Can anyone else confirm this as well?

**Comment by harvastum** [comment] 2022-04-01 03:30
Thank you @Airradda, it does work for me!
However, @hikchoi I do not see why I should not have the possibility to use both dark mode and reduced motion mode with Dendron. I also do not understand how reverting VS Code version is a valid reason to disregard this bug.  
Just in case; do I understand correctly that your advice is to just use an older version of the editor? Please elaborate on that.

**Comment by hikchoi** [comment] 2022-04-01 15:28
> Thank you @Airradda, it does work for me! However, @hikchoi I do not see why I should not have the possibility to use both dark mode and reduced motion mode with Dendron. I also do not understand how reverting VS Code version is a valid reason to disregard this bug. Just in case; do I understand correctly that your advice is to just use an older version of the editor? Please elaborate on that.

We mark issues as they get resolved with a `status.info-needed`, which will auto-close issues after a certain amount of time. Since this issue was resolved in a discord chat, I went ahead and resolved it that way. Please note that at the time of resolution we didn't have the knowledge of reduced motion mode (thanks for pointing that out, @Airradda).

The auto-close bot will be stopped once the issue creator responds with additional comments which would indicate that this is still an outstanding issue _for them_.

I am by no means saying you should stick to an older version of VSCode. This simply means at the time, the immediate issue on the poster's end was resolved.

> I do not see why I should not have the possibility to use both dark mode and reduced motion mode with Dendron.

Now that we know that VSCode has introduced a user setting that honours the OS level preference of reduced motion, we can investigate if this can be prevented on Dendron's end.

A quick look at the media queries we use when rendering webviews do show that we set no preference for removing motion-based animations. So I am suspecting this is caused upstream with VSCode itself. We as extension authors have no control over the VSCode's DOM so our capabilities are a bit limited here.

@harvastum, do you mind creating a separate issue so we can properly track this and investigate further? For housekeeping purposes it would be preferable if this is separated from the current issue.

I apologize if my original response came off as dismissive of this issue. That was not my intention. I believe this was caused by the lack of context given in my comments.

**Closed** 2022-04-03 16:08 UTC
Labels: type.bug, scope.markdown, status.info-needed

**Comment by alefteris** [comment] 2022-04-12 13:27
@hikchoi Could you please re-open this issue or link here the new one that you asked to be created?

The dendron preview apart from the light colors it's also made mostly unreadable. For example table borders are not visible etc. So it's not just an aesthetic issue. VS Code might have a bug with the auto detection of reduced motion setting, but even if it's enabled, dendron preview should still render correctly. I'm using dendron/vs code on Linux using KDE with a dark theme.

Also affected it the calendar widget that is getting displayed with a light theme, should I open a separate issue for that?

**Comment by hikchoi** [comment] 2022-04-12 13:36
@alefteris 

I don't believe the user above has created a new issue for this.

We're happy to track it as a separate issue than this one. We can then keep track of it better internally and investigate further.

Like I mentioned above, we are not dismissing this problem. Marking issue as such is part of a triaging effort to keep many of our issues at a manageable state. 

It would be awesome if you could create a new issue with the problems you described in your comments.

**Comment by alefteris** [comment] 2022-04-12 14:36
I've opened a new issue at https://github.com/dendronhq/dendron/issues/2738. Thanks :)
