### ISSUE TITLE
Rename Note fails with error: "Cannot read property 'forEach' of undefined"

### ISSUE THREAD

**Issue by DanielHZhang** [dendronhq/dendron#338] opened 2020-11-12 19:21 UTC
**Describe the bug**
Attempting to rename a note via the command palette throws an error and deletes the file you were attempting to rename. This occurs irrespective of the filename casing as described in #250.

**To Reproduce**
1. Initialize an empty dendron workspace
2. Use the command palette "Markdown Notes: New Note" to create a new note (e.g. some.example.note)
3. With the note window in focus, use the command palette "Dendron: Rename Note" (e.g. some.example.note -> some.example)
4. Fails with error "Cannot read property 'forEach' of undefined".

**Expected behavior**
The note is renamed successfully without being deleted.

**VSCode**
Dendron extension version 0.15.0
Dendron markdown notes extension version 0.0.17
VSCode Version: 1.52.0-insider (user setup)
Commit: 050a123750e4ef4009930d0da1ff7a1a6441d4f3
Date: 2020-11-12T05:43:04.852Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

** Dendron Log file**
[dendron.log](https://github.com/dendronhq/dendron/files/5532714/dendron.log)

**Comment by kevinslin** [comment] 2020-11-13 15:16
Thanks for the issue. This was just brought to my attention and will be fixed this weekend!

**Comment by osadasami** [comment] 2020-11-14 14:14
Same problem. I have removed all default dendron's notes and add one note `foo.bar`. Then I have tried to `Rename Note` or `Refactor Hierarchy` and got the error `Cannot read property 'forEach' of undefined`

Dendron version `v0.15.0`

**Comment by kevinslin** [comment] 2020-11-14 14:50
Thanks for catching. This is a regression with our current set of starter documents. Will be fixed this weekend!

**Comment by kevinslin** [comment] 2020-11-16 04:50
this should be fixed in 0.16. @osadasami @DanielHZhang could you confirm if you still see this issue?

**Comment by DanielHZhang** [comment] 2020-11-16 05:41
`Dendron: Rename Note` is still throwing an error for me in `v0.16.0` after following the original reproduction steps. However, it no longer deletes the current note in focus. Instead, it merely outputs an error notification: `{"ctx":"h:run","err":{}}`

**Relevant output:**
```
info: {"ctx":"h:run","msg":"pre-execute"}
info: {"ctx":"RenameNoteV2a","msg":"enter","opts":{"files":[{"oldUri":{"$mid":1,"fsPath":"vault\\test.foo.bar.md","_sep":1,"external":"file:///vault/test.foo.bar.md","path":"/vault/test.foo.bar.md","scheme":"file"},"newUri":{"$mid":1,"path":"/vault/test.foo.md","scheme":"file"}}],"silent":false,"closeCurrentFile":true,"openNewFile":true}}
error: {"ctx":"h:run","err":{}}
info: {"ctx":"RenameNoteV2a","msg":"exit"}
```

**Full logs:**
[dendron.log](https://github.com/dendronhq/dendron/files/5544328/dendron.log)

**Comment by osadasami** [comment] 2020-11-16 06:56
Same as @DanielHZhang. Update dendron to version `v0.16.0` and after rename or refactor hierarchy got an error
```
{"ctx":"g:run","err":{}}
```

**Comment by kevinslin** [comment] 2020-11-16 15:57
@DanielHZhang, when you are renaming the note, does the note have dendron frontmatter attached?

it should look like the following
```
---
id: 22efbe89-9411-40fa-917f-f9cabc1f4abd
title: Foobar
desc: ''
updated: 1605542205739
created: 1605542205739
---
```

the error you're getting is because dendron couldn't find metadata for the note. whenever you create a note using lookup or by opening a wiki-link, the metadata is automatically added. it is not added for notes that are manually created

**Comment by DanielHZhang** [comment] 2020-11-16 18:02
I have only been creating notes via the command `Markdown Notes: New Note`. This is the result from running that command for a note named `example.foo.bar`:

```markdown
---
id: 8d6ead03-bd2a-4675-8592-4406a74c5d89
title: Bar
desc: ''
updated: 1605504522848
created: 1605504522848
---
# Bar

```

**Comment by kevins8** [comment] 2020-11-17 06:09
Ah. Markdown Notes: New Note uses a different engine than Dendron. It's not
indexed until the next time workspace is reloaded. We're going to be
integrating markdown notes related functionality with dendron equivalents
starting with the next release. Can you see if creating a new note using
`Dendron: Lookup` still results in this error?

**Comment by DanielHZhang** [comment] 2020-11-17 07:25
Ah, I wasn't aware that `Dendron: Lookup` was the preferred method for creating notes. Perhaps it could be renamed to `Dendron: Lookup or Create` to make it more intuitive for new users?

Creating a new note via `Dendron: Lookup` and then renaming it no longer errors. Renaming works successfully for regular names, but still can break on a couple edge cases:
- renaming the note to an empty string (clearing the rename input field and pressing enter)
- including any invalid Windows filename character in the new name: `"*<>?\|/:`

These edge cases produce variations of this error:
```
{"ctx":"h:run","err":{"name":"Error","message":"cannot open file:///Dendron_debug/vault/.md. Detail: Unable to read file 'Dendron_debug\\vault\\.md' (Error: Unable to resolve non-existing file 'Dendron_debug\\vault\\.md')"}}
```

**Comment by kevinslin** [comment] 2020-11-17 16:00
It's been a source of confusion before and I'm trying to figure out how to make it more obvious. 

We are removing the markdown-notes extension dependency the coming week and folding all related functions into Dendron which will remove one source of error

As for making `Lookup` more obvious - I'm hesitant to rename the command to `Lookup or Create` as now the name becomes a tad too verbose. We just slimmed down the getting started vault from 100+ notes to 3 notes. I'm thinking of opening with an example of using lookup to find and create might help.

Also open to other suggestions :)

And thanks for mentioning the other edge cases. Lets keep this ticket open then until we fix them.

**Comment by kpathakota** [comment] 2021-04-25 11:02
I think we agreed this is due to Windows vs. Mac posix naming and that is the *correct* fix for this. I still run into this from time to time despite updating my dendron.yml with Windows path name conventions.

**Closed** 2021-05-06 17:08 UTC
Labels: type.bug
