### ISSUE TITLE
Wikilinks with "end" anchor are not correctly formatted

### ISSUE THREAD

**Issue by alex-ess** [dendronhq/dendron#2818] opened 2022-04-25 19:58 UTC
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [x] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

The Wikilinks with "end" anchor are not formatted correctly.

When used with [[note#header]] the link is correctly formatted but when used with "end" anchor [[note#header:#*]] it is formatted like a "missing note" but the Link is working fine.

## To Reproduce

1. Create 2 Wikilink with anchor
2. Create one with "end" anchor, #header:#*
3. The wikilink with "end" anchor is formatted incorrectly (yellow)

## Expected behavior

Both links should be blue (complete link) 

## Screenshots

![image](https://user-images.githubusercontent.com/54401257/165162622-87e62350-3892-4e57-a6ba-e64a2aac45f1.png)

## Desktop (please complete the following information)

- Versions (all that apply to bug):
  - VS Code version:

**Comment by kevinslin** [comment] 2022-04-26 02:08
thanks for the issue. actually, checking the syntax, we don't actually support this. we support a note reference including a range (`![[foo#head:#*]]`) but a regular wikilink to a range is not valid

**Comment by alex-ess** [comment] 2022-04-26 05:24
Yeah, the end anchors are most useful when using the ref! annotation. It just stumbled upon it as I was taking my screenshots for the backlink feature request and last week when I was scribbling down notes for our chat. What confused me a little was that the link was working fine and even the hover-text was correctly cut of at the next header.

![image](https://user-images.githubusercontent.com/54401257/165225510-0e515457-3720-4a93-98e5-c9517ea8042b.png)

So, I figured here might be some formatting syntax missing since usually the yellow links have a "missing note" hover-info

![image](https://user-images.githubusercontent.com/54401257/165226070-d0b93003-e5d2-4e3b-b842-475228501c12.png)

**Comment by kevinslin** [comment] 2022-05-03 00:32
Yeah, this is undefined behavior. dendron tries to parse the known part of the anchor when its a wikilink. i'll close this issue for now since its working as intended

**Closed by kevinslin** 2022-05-03 00:32 UTC
Labels: type.bug, scope.markdown, status.info-needed
