### ISSUE TITLE
Import metadata from Obsidian

### ISSUE THREAD

**Issue by cliftonfoster** [dendronhq/dendron#2018] opened 2021-12-31 15:18 UTC
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [x] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

Importing from Obsidian does not bring in any metadata.

## Describe the solution you'd like ##

Metadata can vary by individual so I do not expect a universal fix-all. If the option were available to map current metadata names to new one or ones that already exist in Dendron, that would be great. For example, I had my own format for date created so this one may not be easily imported as 'created' in Dendron, but maybe as a custom field so that at least it is not lost. 
    (Here is my format for created - created: 2021-08-22 05:58.221 (Sunday) -07:00)
But other metadata would be nice to migrate as is. In Obsidian I have a metadata name of 'tags' where I put my tags. This would be nice to keep or migrate if there were some way to do that by adding a hashtag to the beginning of each.
    (Here is my format for tags - tags: poem memory-verse emerson)

## Describe alternatives you've considered ##

Alternatively, it might be nice to just have all the metadata brought over without mapping or converting any of it. Maybe my existing id might be renamed to obsidian-id and my current name of created might be obsidian-created, etc. That way I could at least keep my old metadata.

This feature could also just ask during import which metadata to keep and bring over so I could only specify my tag and alias metadata and not bring over my id or name metadata.

## Additional context ##

none

**Comment by Harshita-mindfire** [comment] 2022-01-03 17:31
Thanks @cliftonfoster for reporting the issue. I agree this would be a great enhancement for the pod to support metadata import.

**Comment by ScriptAutomate** [comment] 2022-01-05 03:31
May be a duplicate of:
- https://github.com/dendronhq/dendron/issues/659

**Comment by Harshita-mindfire** [comment] 2022-01-05 06:07
Yes, intersects with point 1 of it. @cliftonfoster can you check if #659 coincides with your issue? If so, can we track this issue with it?

**Closed** 2022-01-13 18:09 UTC
Labels: type.enhancement, status.info-needed, scope.pod
