### ISSUE TITLE
Journal sorting in Loookup does not work

### ISSUE THREAD

**Issue by SR--** [dendronhq/dendron#2661] opened 2022-03-31 08:16 UTC
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [x] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Expected behaviour is for the journal entries to be sorted by date, from newest to oldest. At the moment, they do not seem to be sorted or sorted differently.

## To Reproduce

Type in the Lookup.

## Expected behavior

Ordered sorting.

## Screenshots

![image](https://user-images.githubusercontent.com/1008059/161009457-99f7a737-3e2f-4b2e-aaa9-e219424a5f07.png)

## Desktop (please complete the following information)

- OS: win
- Versions (all that apply to bug):
  - Dendron Extension: 88
  - VS Code version: 1.66

## Additional context

As discussed on [Discord](https://discord.com/channels/717965437182410783/735365126227493004/958956883014713415).

**Comment by hikchoi** [comment] 2022-03-31 15:47
@SR-- Could you share the exact query you typed in for lookup? I can't seem to reproduce this issue on my end: 
![image](https://user-images.githubusercontent.com/1219789/161096496-1b5fb5cb-16a9-4f31-b7e1-9553973d5930.png)

**Comment by micharris42** [comment] 2022-03-31 18:43
I am not sure if this is a bug. I think it may be the intended behavior.

According to the [Dendron Wiki](https://wiki.dendron.so/notes/84a0366a-eab5-4862-9bef-360f92a196dc/#sort-ordering), Lookup results are sorted by FuseJS match score, whether or not the note is a stub, by Levenshtein distance, and finally by most recently updated. 

If journal notes are not updated chronologically, then they will not be displayed chronologically. @SR--, for the journal notes shown in your screenshot above, can you check the "updated" field of their respective frontmatter? I would expect they are being sorted by date updated. 

Perhaps the option could be added for Lookup results to be sorted by title and/or date created?

**Comment by SR--** [comment] 2022-03-31 23:38
@micharris42 Yes, that sounds right to me. It is also reasonable for most notes but maybe one could force the journal or meeting notes to be always newest first?
@hikchoi I just started typing 'journal'

**Comment by hikchoi** [comment] 2022-04-01 15:10
Thanks for pointing that out @micharris42. Yes. that would be the case.

@SR-- Do you mind closing this and creating a separate feature request for forcing the sort order? You could link this issue there to preserve the context.

**Comment by SR--** [comment] 2022-04-06 11:04
I think I shall just close this without making a suggestion issue. I am not sure if it is need and what to ask for now that I understand the reason.

**Closed** 2022-04-06 11:04 UTC
Labels: type.bug, scope.lookup
