### ISSUE TITLE
Dendron in Visual Studio Code for web

### ISSUE THREAD

**Issue by WickM** [dendronhq/dendron#2523] opened 2022-03-03 20:45 UTC
## Please select if your request is either something new or an enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [x] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

A clear and concise description of what the problem is. E.g. I'm always frustrated when [...]

## Describe the solution you'd like ##
I would like to use Dendron in the browser with https://code.visualstudio.com/docs/editor/vscode-web. I love Dendron more than anything and have been using it privately for some time. Unfortunately, I can't use it at work because I don't have and won't get VisualStudio code there.

**Comment by ScriptAutomate** [comment] 2022-03-03 22:34
Duplicate of: 
- #1777

Feel free to add to the conversation there :)

**Closed by ScriptAutomate** 2022-03-03 22:34 UTC
Labels: type.feature, status.triage-needed, scope.workspace
