### ISSUE TITLE
Easily create attachments to notes

### ISSUE THREAD

**Issue by ddbrierton** [dendronhq/dendron#697] opened 2021-05-05 16:06 UTC
## Please Select if your Request is Either something new or an Enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applys to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

When writing literature notes I often have a PDF of the article in question, sometimes I have even annotated it directly. It would be very useful to have a simple way to attach the file to my note.

## Describe the solution you'd like ##

My ideal scenario would be a `Dendron: Create attachment` command, which would open a file selector. I choose the file I want to attach, and Dendron copies it to the `assets` folder. In doing so the name would be converted to kebab-case with all non-alphanumeric characters removed and have the date and time pre-pended.

Rather than inserting a link directly into the note (one option, indeed), perhaps there could be an `attachments:` field in the YAML front matter, allowing multiple attachments to be displayed together in a distinctively styled way in the preview. For example icons representing the mime-types of the attachments could be used.

It is essential that such attachments be easily openable in suitable external applications by directly clicking in the preview pane (not currently possible).

## Describe alternatives you've considered ##

I have tried manually copying PDFs into the `assets` folder and then manually adding links to the note. However, neither markdown:

```md
[Local PDF](assets/example.pdf)
```

nor HTML

```html
<a href=“assets/example.pdf” type=“application/pdf”>Local PDF</a>
```

generate a link in the preview which can actually open the PDF. Similarly cmd-clicking the link in the editor also fails to open the PDF. The only way to open it from inside VS Code is to right-click the file in the VS Code file explorer, select “Reveal in Finder” and then open the file from the Finder.

**Comment by kpathakota** [comment] 2021-05-06 12:20
Duplicate of #575. This has good info though which we should take into account when implementing the command.

**Closed by kpathakota** 2021-05-06 12:20 UTC
Labels: area.create, status.triage-needed, type.feature
