### ISSUE TITLE
Within reference links with boundaries, links at the start and end of those boundaries are not clickable

### ISSUE THREAD

**Issue by bomboloni** [dendronhq/dendron#1274] opened 2021-09-03 04:05 UTC
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ x] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ x] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

I've published one of my vaults and I'm using range reference links with boundaries to embed sections of one page into another, like this ![[topics#^start:#^end]]. The sections begin and end with links. Anywhere these reference links are used, neither the first nor the last links are clickable. Is there a way to fix this?

It happens in three different instances here: https://100devsresources.netlify.app/ if it helps to see what I'm talking about.

And here is the vault on GitHub: https://github.com/bomboloni/100Devs-resources

## To Reproduce

It shows up on my published website anywhere I use the `![[page#^start:#^end]]` construction.

I used this command to build the site `npx dendron-cli buildSiteV2 --stage prod`

## Expected behavior

I expect all links within reference links to be clickable when they appear.

## Screenshots

It won't show in a screenshot but you can go here to see: https://100devsresources.netlify.app/

## Desktop (please complete the following information)

MacOs 10.15.7
Safari 14.1.2
Firefox Developer Edition 92.0b9

## Additional context

I first asked about this on discord here: https://discord.com/channels/717965437182410783/735365126227493004/883095486708473887
and was advised to make this report.

## Dendron Log file

Please attach the output of `>Dev:Dendron: Open Logs` here

[dendron.log](https://github.com/dendronhq/dendron/files/7103246/dendron.log)

**Comment by jonathanyeung** [comment] 2021-09-03 04:15
Thanks for filing this issue - we'll take a look shortly.

**Comment by SeriousBug** [comment] 2021-09-03 08:47
Thanks for the report -- I can see that the issue is some elements that cover up the start and end of the reference. I found a fix for this, and will try to add it to Dendron as soon as possible.

**Comment by bomboloni** [comment] 2021-09-04 06:15
That's great to hear, thank you!

**Comment by SeriousBug** [comment] 2021-09-07 21:56
This has now been fixed with Dendron 0.58. Please let us know if the issue still happens, otherwise this issue will automatically close in a few days.

**Comment by bomboloni** [comment] 2021-09-09 22:26
I've just updated Dendron and VSCode, and restarted VSCode. I'm still seeing the same issue both in my local previews and the website.

**Comment by SeriousBug** [comment] 2021-09-10 04:50
I just tried reproducing this issue, it no longer happens to me both in the preview and published website. I also tried pulling your repository and building it locally, that works as well.

For a sanity check, could you try the following in a terminal?
- Build the site with `dendron buildSiteV2 --serve` and check if the links work on that website preview
- If the links still don't work, run `dendron --version` to check that the version is `0.58` or higher
- Rebuild the website if you haven't done so already, and I'll take another look at it

**Comment by bomboloni** [comment] 2021-09-10 18:41
Sanity check partially confirmed! I had forgotten to update the Dendron CLI. 

`dendron buildSiteV2 --serve` gives me a local preview site that does work as expected. 

However, after updating my repo and pushing to GitHub, my published website is still showing the old behavior. On Netlify, I cleared the cache and redeployed using `npx dendron-cli buildSiteV2 --stage prod`

**Comment by bomboloni** [comment] 2021-09-10 18:42
Sanity check partially confirmed! I had forgotten to update the Dendron CLI. `dendron buildSiteV2 --serve` now gives me a local preview site that does work as expected. However, after updating my repo, my published website is still showing the old behavior. On Netlify, I cleared the cache and re

**Comment by bomboloni** [comment] 2021-09-10 18:43
Adding that I am now running version 0.58.4-alpha.3

**Comment by kevinslin** [comment] 2021-09-20 23:33
We had a regression with the last 11ty publishing. Can you update to the latest version of the CLI and 11ty by following the setup instructions [here](https://wiki.dendron.so/notes/1399b5d2-28fb-4077-aa5f-c8edbe52bc5d.html#setup?

**Closed** 2021-10-03 23:12 UTC
Labels: type.bug, area.publish, area.retrieve
