### ISSUE TITLE
Tagging broken

### ISSUE THREAD

**Issue by funnym0nk3y** [dendronhq/dendron#787] opened 2021-06-03 13:04 UTC
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [x] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

I used to tag my notes with formated tags. With update 0.44 the tags aren't shown but the title of the viewed note, so if a note is included in another note both tags show the title of the currently viewed note.

**Comment by kpathakota** [comment] 2021-06-04 10:10
Yup, just saw this too. Will fix this release. Duplicate of #790

**Closed by kpathakota** 2021-06-04 10:10 UTC
Labels: area.retrieve, status.triage-needed, type.bug
