### ISSUE TITLE
Notes cannot be opened from graph view

### ISSUE THREAD

**Issue by Simon-Claudius** [dendronhq/dendron#452] opened 2021-01-17 04:10 UTC
In Dendron version 0.24.0, clicking a given node in the graph view doesn't open/navigate to its associated note in the editor. Version 0.23.0 works as expected.  

**Steps to reproduce the behavior:**
1. Open a Dendron workspace
2. Run `dendron.showNoteGraph`
3. Left-click on a node in the graph view that has an associated markdown file (i.e. isn't virtual)

**Expected behavior**
The editor pane opens/switches to the associated markdown file.

**Comment by kevinslin** [comment] 2021-01-17 18:49
Thanks for catching this. This was a regression since we updated our core package (dendron) and not the markdown links package. 
This has now been fixed with dendron-markdown-links v0.6.19. 

You can also see the updated docs [here](https://dendron.so/notes/587e6d62-3c5b-49b0-aedc-02f62f0448e6.html)

Will leave this open for confirmation by user. If this has fixed the issue, feel free to close this issue :)

**Closed** 2021-01-18 18:37 UTC
Labels: type.bug
