### ISSUE TITLE
Add a way to display link metadata in editor, preview and publishing

### ISSUE THREAD

**Issue by rlh1994** [dendronhq/dendron#2851] opened 2022-04-28 16:16 UTC
## Please select if your request is either something new or an enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [x] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

When I look at the backlinks section I do not know the context in which a note was linked, for some systems (where for example notes are linked under specific headings in a templated note) this means I may have to open the notes to understand what section they were linked in.

## Describe the solution you'd like ##

Some way to identify some context around how the note was linked - possibly either by manually adding metadata via the link itself, or additional functionality in the backlink to provide the context (e.g. the header it is under). Ideally this would be visible in the published site as well as in VSCode and work for backlinks as well as the actual links.

This could then be expanded to include things like weight of link, or any other metadata really.

## Describe alternatives you've considered ##

Currently I either have to open all the notes in the backlinks, or have to duplicate the linking in the other direction to call out a subset of the backlinks (which might then become out of date).

**Comment by aleksey-rowan** [comment] 2022-04-28 17:35
Hey, @rlh1994, thank you for the request. There were a few tickets addressing a similar problem. Could you please check if any of the following issues cover what you are suggesting?

- https://github.com/dendronhq/dendron/issues/2038
- https://github.com/dendronhq/dendron/issues/1916

**Comment by rlh1994** [comment] 2022-04-28 17:50
Hi @aleksey-rowan, you're right sorry it's probably similar in concept to either of those - I guess the additional request in this would be to ensure that it's visible in published sites and display some of it by default in the backlink section instead of the focus being on the graph view or even searchability. 

My use case is a subset of those listed in the others I think; I'm focused more on wanting understand from within a note (published or in VSCode) how it's linked to by others without having to leave that note. If that makes sense?

**Comment by aleksey-rowan** [comment] 2022-04-28 18:19
Yeah, that makes sense. I just wanted to make sure this is not a full duplicate of the ones submitted before.

**Comment by SeriousBug** [comment] 2022-04-28 20:49
Thanks for the suggestion! I'll rename the issue in consideration with the existing issues.

**Comment by nklamann** [comment] 2022-05-05 15:21
I look at the problem as an aspect of the BACKLINKS View in VSCode. There I would suggest to show for each backlink the Information: 
* filename
* Number of links (because it already exists, I personally find it not so important)
* Title
* Vault 
* Header, where the link is under (as @rlh1994 suggested)

Maybe that is too much for such a view but that would be ideal

**Closed** 2023-02-06 16:18 UTC
Labels: type.feature, scope.markdown
