### ISSUE TITLE
Dendron Tree widget not updating on new note creation

### ISSUE THREAD

**Issue by Cmhorn** [dendronhq/dendron#670] opened 2021-04-27 13:11 UTC
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [x] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x ] Misc (Choose this if your not sure)

## Describe the bug
Tree widget does not automatically refresh to reflect the most current hierarchy.

## To Reproduce
1) Ctrl+L to create a new note
2) Ctrl+S to save
3) Observe the Dendron Tree widget

## Expected behavior

I would expect the new hierarchy to be reflected in the Tree widget. The Tree widget only updates on reboot or through Dendron Rebuild Index command being explicitly called. 

## Desktop (please complete the following information)

- OS: PopOS 20.10
- Browser: Firefox
- Version: 0.39.0

## Dendron Log file

Log file contains information I do not consent to share.

**Comment by flammehawk** [comment] 2021-04-27 14:08
I can Reproduce it and a look through my diagnostic log makes it seem like the event to refresh the tree gets emitted by the VaultWatcher but the Treeview does not refresh its data.

**Comment by kevinslin** [comment] 2021-04-27 23:39
Yeah, this is a bug. Will be fixed in next weeks release

**Comment by kevinslin** [comment] 2021-05-05 17:05
this has been fixed in 0.40

**Closed by kevinslin** 2021-05-05 17:05 UTC
Labels: area.misc, area.retrieve, status.wip, type.bug

**Comment by lukors** [comment] 2021-09-27 05:13
I was doing the tutorial and ran into this bug in `v0.60.1`.

**Comment by aleksey-rowan** [comment] 2021-09-27 11:56
Which tree widget are you using? V1 or V2? Actually, looks like it's broken in both now :/

**Comment by lukors** [comment] 2021-09-27 15:43
Do we make a new issue or will someone re-open this one? :)

**Comment by aleksey-rowan** [comment] 2021-09-27 15:54
I think it's easier to make a new one and refer back to this one.
