### ISSUE TITLE
Clicking on local pdf link in preview doesn't open it

### ISSUE THREAD

**Issue by Gorzen** [dendronhq/dendron#2306] opened 2022-01-28 20:25 UTC
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [x] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

I have a pdf in `assets` folder. In one note, I link the pdf like this : `[Article title](./assets/article.pdf)`. If I click on the link in the preview nothing happens. I would expect it to open the PDF in my default app or in VSCode.

Note: If I do `cmd+click` on the editing pane, it opens the pdf in VSCode.

## To Reproduce

1. Add link to a local pdf in a note
2. Open preview
3. Click on the link to pdf
4. Witness that nothing happens

## Expected behavior

The PDF should open in default app or VSCode in editing pane.

## Desktop (please complete the following information)

- OS: macOS 12.1

**Comment by SeriousBug** [comment] 2022-01-28 21:49
Thanks for the report! I added it to our backlog and will make sure to prioritize this within the next few weeks.

**Comment by SeriousBug** [comment] 2022-02-17 08:58
I believe this is a duplicate of #1695.

**Closed** 2022-03-05 10:50 UTC
Labels: type.bug, status.info-needed, scope.views
