### ISSUE TITLE
limit lookup by vault name

### ISSUE THREAD

**Issue by kinnison** [dendronhq/dendron#2583] opened 2022-03-16 20:04 UTC
## Please select if your request is either something new or an enhancement ##

- [x] Enhancement of an existing Feature.
- [ ] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [ ] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [x] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

I have multiple vaults in a workspace, and since two of them are journals (one personal, one work) I often find myself struggling to differentiate between the entries in each vault.

## Describe the solution you'd like ##

It would be amazing if I could restrict the lookup by vault name, ideally by typing.  A prefix in lookup would be great, perhaps either `vault-name/` or at "worst" `dendron://vault-name/`.

## Describe alternatives you've considered ##

I'm not sure there's an easy alternative, I could rename the entire hierarchy in one vault, but that feels defeatist and I'm sure I'd end up wanting this again in the future.

**Comment by aleksey-rowan** [comment] 2022-03-17 00:57
Hey, @kinnison, thank for the request. There are already an issue that I think matches your suggestion very closely and asks for an option to hoist a subtree (where you filter the hierarchy tree and restrict the lookup to a certain hierarchy):

- https://github.com/dendronhq/dendron/issues/664

It makes sense to extend this ability across the multi-vault setups (letting the user hoist whole vaults in addition to hoisting just select hierarchies) as well to achieve what you are asking for.

Also there are two other related issues: one is asking for an option to exclude certain hierarchies (`archive` in particular) from being indexed/generating backlinks and an option to exclude hierarchies from lookup (sort of the reverse of hoisting):

- https://github.com/dendronhq/dendron/issues/2561
- https://github.com/dendronhq/dendron/issues/696

And as I was writing this answer, I realized there is an exact duplicate of this issue:

- https://github.com/dendronhq/dendron/issues/1031

I think #1031 can be closed--even though it's an older issue--as this one has more information.

**Comment by kevinslin** [comment] 2022-03-17 21:55
agree with @aleksey-rowan . @kinnison, could you upvote #1031? closing this as a dup of #1031

**Closed by kevinslin** 2022-03-17 21:55 UTC
Labels: type.enhancement, status.triage-needed, scope.lookup
