### ISSUE TITLE
Activating extension dendron.dendron failed

### ISSUE THREAD

**Issue by ronaldosy** [dendronhq/dendron#3927] opened 2023-05-05 08:36 UTC
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [X] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## To Reproduce

1. Open VS Code
2. Click on 'Extensions'
3. Search for Dendron
4. Click Install
5. No Welcome Page appear
6. Open command pallete
7. Type Dendron: Launch Tutorial
8. Error Command 'Dendron: Launch Tutorial' resulted in error

## Expected behavior
Per wiki Welcome page should appear after installation 

## Screenshots

N/A

## Desktop (please complete the following information)

- OS: Microsoft Windows [Version 10.0.19045.2846]
- Versions (all that apply to bug):
  - Dendron Extension: v0.122.
  - VS Code version: 1.78.0
  - Dendron CLI:

## Additional context

The cause of the error \\?\c:\Users\ronaldo\\.vscode\extensions\dendron.dendron-0.122.0-win32-x64\dist\node_sqlite3.node is not a valid Win32 application.

## Dendron Log file
[vscode.log](https://github.com/dendronhq/dendron/files/11404563/vscode.log)

**Comment by dansorgh** [comment] 2023-05-05 13:14
I have experienced this as well - if it helps: when inspecting `Developer: Show Running Extensions` in VSCode Dendron just stays stuck on "Activating". Only applies to the latest version (as noted above) and also on a similar version of Windows - reverting the version of the extension restores functionality.

**Comment by dansorgh** [comment] 2023-05-05 14:13
actually this is probably a duplicate of #3926

**Comment by kevinslin** [comment] 2023-05-05 21:15
yep, closing this as dup

**Closed by kevinslin** 2023-05-05 21:15 UTC
Labels: type.bug, status.triage-needed, scope.workspace
