### ISSUE TITLE
Issue with Dendron Preview on Windows

### ISSUE THREAD

**Issue by sahil48** [dendronhq/dendron#2074] opened 2022-01-06 14:20 UTC
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [x] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

![image](https://user-images.githubusercontent.com/6100774/148396524-5736f3c6-cbf1-4ed6-a65f-d506e42c2f92.png)

I created a vault in an iCloud Drive Folder on Windows.

Dendron Preview does not work with these files

## To Reproduce

1. Initialize a Dendron Workspace in an iCloud Drive folder
2. Create a vault
3. Add a file to that vault
4. Run Dendron Preview

## Expected behavior

The Preview would work
## Desktop (please complete the following information)

- OS: Windows
- Browser: VSCode with dendron installed
- Version: 1.63.2

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` here

**Comment by sahil48** [comment] 2022-01-06 14:23
More Information:

Upon Closing and Reopening Dendron, the preview worked, but I still get the same error.

![image](https://user-images.githubusercontent.com/6100774/148397490-2412afc2-3bf8-4a9e-979b-07d148e559d7.png)

**Comment by jwallander** [comment] 2022-01-06 14:55
Have the same problem. An extra C:\ is prefixed to the path no matter where the workspace repo is checked out.

error while running command: ENOENT: no such file or directory, open 'C:\D:\jwkb\vault\root.md'
error while running command: ENOENT: no such file or directory, open 'C:\c:\Users\jwall\Documents\jwkb\vault\root.md'
[dendron.log](https://github.com/dendronhq/dendron/files/7822603/dendron.log)

**Comment by kevinslin** [comment] 2022-01-06 21:55
Thanks for the issue. Will investigate

**Comment by pappattila** [comment] 2022-01-08 14:32
same problem when using it in windows
"error while running command: ENOENT: no such file or directory, open 'C:\c:\Users\Durbincs\Dendron\vault\tutorial.1-navigation-basics.md'"

no problem when using it in wsl remote

**Comment by jeffbarr** [comment] 2022-01-11 00:22
This is happening to me as well.

**Comment by SeriousBug** [comment] 2022-01-11 23:27
Hi everyone, this bug should now be fixed with Dendron 0.77. This issue will stay open for a few more days in case anyone continues to experience this problem.

**Comment by sahil48** [comment] 2022-01-14 23:59
Does this need to stay open?

**Comment by SeriousBug** [comment] 2022-01-15 00:01
The bug should be fixed. Are you still experiencing it after updating?

**Comment by SeriousBug** [comment] 2022-01-15 01:54
Please reopen the issue if you are still having this bug after updating, otherwise the bug is solved and the issue is closed.

**Closed by SeriousBug** 2022-01-15 01:54 UTC
Labels: type.bug, scope.views
