### ISSUE TITLE
Hitting tab in Lookup Note to complete the path and then adding to the path does not work

### ISSUE THREAD

**Issue by HopperTech** [dendronhq/dendron#2579] opened 2022-03-16 15:09 UTC
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [x] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

While using the fuzzy search feature of Lookup Note to find a specific path, I try to use the tab feature to complete the path and then append a new note to that path. Hitting enter the original path is opened and not the desired newly created note. 

## To Reproduce

1. Open the Lookup note
2. Do a fuzzy search to find a particular path
3. Hit the tab key to populate the search bar with that path
4. Append a new note to that path i.e. '.newnote' 
5. Hit enter 
6. The found path is opened 

## Expected behavior

I expect that the desired note is created

## Desktop (please complete the following information)

- OS: Windows
- Browser (if with published websites; include version): VSCode 
- Versions (all that apply to bug):
  - Dendron Extension: 0.86.1
  - VS Code version: 1.65.2
  - Dendron CLI: N/A

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` here

**Comment by kevinslin** [comment] 2022-03-17 21:57
can reproduce. thanks for the submission, will add to our backlog

**Comment by aleksey-rowan** [comment] 2022-03-23 12:10
Hi, @HopperTech, I'm going to close this as a duplicate of 

- https://github.com/dendronhq/dendron/issues/2550

Please, feel free to upvote or leave a comment on the linked issue.

**Closed** 2022-03-23 12:11 UTC
Labels: type.bug, status.duplicate, scope.lookup
