### ISSUE TITLE
Math Equations are rendered twice, once as plain text

### ISSUE THREAD

**Issue by zeyuz35** [dendronhq/dendron#1746] opened 2021-11-19 10:02 UTC
## Please select the area your bug applies to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [x ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

Dendron built websites since the new NextJS template incorrectly renders equations twice - one normally, and once 

## To Reproduce

Publish any note with inline equations. This can even be seen on the Dendron wiki for equations
https://wiki.dendron.so/notes/b1919663-cc48-4054-b0cf-4b26fe444907/

## Expected behavior

Equations to be rendered once normally.

## Screenshots

![Screenshot from 2021-11-19 21-00-32](https://user-images.githubusercontent.com/19887504/142604190-51440825-f486-42e0-85fc-75d46d096564.png)

## Desktop (please complete the following information)

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` her

e

**Comment by Stedag** [comment] 2021-11-21 23:24
![image](https://user-images.githubusercontent.com/5147273/142782744-f1e814e8-6a28-48b3-ac27-2b2a2629c13a.png)
It seems like a decent workaround for now could be adding:
```
const elements = document.getElementsByClassName("katex-html");
while(elements.length>0) elements[0].remove();
```

**Comment by hikchoi** [comment] 2021-11-22 07:01
Thanks for bringing this up. I can reproduce this.
Looks like this also happens with our preview.

We'll let you guys know once we fix this issue 🙏🏼

**Comment by kevinslin** [comment] 2021-11-23 22:08
this should be fixed in v70 of Dendron. please post here if not, otherwise this issue will auto close in 4 days

**Closed** 2021-11-26 22:24 UTC
Labels: type.bug, area.publish, status.info-needed
