### ISSUE TITLE
Error Initializing

### ISSUE THREAD

**Issue by ebromberg** [dendronhq/dendron#2958] opened 2022-05-23 13:32 UTC
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ X] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Installed the extension and selected create new workspace. Starting Dendron dialog appears, but then get Error Initializing dendron.

## To Reproduce

1. Open Dendron workspace.

## Expected behavior

Dendron initializes successfully.

## Screenshots

Don't have screen shots but here is copy from VSCode output tab for Dendron:
info: {"ctx":"Logger:configure","msg":"exit","logLevel":"info"}
info: {"ctx":"_activate","stage":"prod","isDebug":false,"logLevel":"info","logPath":"c:\\Users\\EBromberg\\AppData\\Roaming\\Code\\logs\\20220523T092704\\exthost1\\dendron.dendron","extensionPath":"c:\\Users\\EBromberg\\.vscode\\extensions\\dendron.dendron-0.95.1","extensionUri":"c:\\Users\\EBromberg\\.vscode\\extensions\\dendron.dendron-0.95.1","workspaceFile":"c:\\Users\\EBromberg\\Dendron\\dendron.code-workspace","workspaceFolders":["c:\\Users\\EBromberg\\Dendron\\vault"]}
info: {"ctx":"DendronExtension","msg":"initialized"}
info: {"ctx":"_activate","msg":"initializeWorkspace","wsType":"CODE","currentVersion":"0.95.1","previousGlobalVersion":"0.0.0","extensionInstallStatus":"INITIAL_INSTALL"}
info: {"msg":"Telemetry is disabled? false"}
info: {"msg":"Segment Residual Cache Path is at c:\\Users\\EBromberg\\AppData\\Roaming\\Code\\User\\globalStorage\\dendron.dendron\\segmentresidualcache.log"}
info: {"ctx":"runMigrationsIfNecessary","changes":[],"workspaceInstallStatus":"NO_CHANGE"}
info: {"ctx":"_activate","platform":"win32","extensions":[{"id":"dendron.dendron","version":"0.95.1","active":true},{"id":"dendron.dendron-paste-image","version":"1.1.0","active":false},{"id":"dendron.dendron-markdown-shortcuts"},{"id":"redhat.vscode-yaml","version":"1.7.0","active":false}],"vaults":[{"fsPath":"vault"}]}
info: {"ctx":"WSUtils.handleServerProcess","msg":"subprocess running","pid":16436}
info: {"ctx":"startServerProcess","msg":"post-start-server","port":52492,"durationStartServer":2601}
debug: {"ctx":"TreeView:getChildren"}
info: {"ctx":"TreeView:getChildren","msg":"reconstructing tree: enter"}
info: {"ctx":"TreeView:getChildren","msg":"reconstructing tree: exit"}
info: {"ctx":"dendron.reloadIndex:run","msg":"pre-execute"}
info: {"ctx":"ReloadIndex.execute","msg":"enter"}
info: {"ctx":"ReloadIndex.execute","durationEngineInit":195}
info: {"ctx":"ReloadIndex.execute","msg":"exit"}
info: {"ctx":"dendron.reloadIndex:run","msg":"post-execute"}
info: {"ctx":"reloadWorkspace","msg":"post-ws.reloadWorkspace"}
info: {"ctx":"reloadWorkspace","msg":"exit"}
info: {"ctx":"postReloadWorkspace","msg":"same wsVersion"}
info: {"ctx":"postReloadWorkspace","msg":"exit"}
info: {"ctx":"setupViews","msg":"init:treeViewV2"}
info: {"ctx":"setupBacklinkTreeView","msg":"init:backlinks"}
info: {"ctx":"activateWorkspace","stage":"prod","msg":"enter"}
info: {"ctx":"togglePluginActiveContext","state":"togglePluginActiveContext: true"}
info: {"ctx":"_activate","msg":"fin startClient","durationReloadWorkspace":3908}
error: {}
error: {"ctx":"showInitProgress","msg":"issue initializing Dendron"}
info: {"ctx":"updateDecorations","payload":{"error":null,"decorationsLength":2,"diagnosticsLength":0}}

## Desktop (please complete the following information)

- Browser (if with published websites; include version): [e.g. chrome, safari]
- Versions (all that apply to bug):
  - Dendron Extension:
  - VS Code version:
  - Dendron CLI:

## Dendron Log file

Please attach the output of `> Dendron:Dev: Open Logs` here
{"level":30,"time":1653312718036,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"Logger:configure","msg":"exit","logLevel":"info"}
{"level":30,"time":1653312718097,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"_activate","stage":"prod","isDebug":false,"logLevel":"info","logPath":"c:\\Users\\EBromberg\\AppData\\Roaming\\Code\\logs\\20220523T092704\\exthost1\\dendron.dendron","extensionPath":"c:\\Users\\EBromberg\\.vscode\\extensions\\dendron.dendron-0.95.1","extensionUri":"c:\\Users\\EBromberg\\.vscode\\extensions\\dendron.dendron-0.95.1","workspaceFile":"c:\\Users\\EBromberg\\Dendron\\dendron.code-workspace","workspaceFolders":["c:\\Users\\EBromberg\\Dendron\\vault"]}
{"level":30,"time":1653312718100,"pid":12732,"hostname":"AP-PF1Y22SP","name":"SegmentClient","msg":"No cache path for Segment specified. Failed event uploads will not be retried."}
{"level":30,"time":1653312718104,"pid":12732,"hostname":"AP-PF1Y22SP","name":"SegmentClient","msg":"user telemetry setting: enabled by config"}
{"level":30,"time":1653312718104,"pid":12732,"hostname":"AP-PF1Y22SP","name":"SegmentClient","msg":"telemetry initializing"}
{"level":30,"time":1653312718104,"pid":12732,"hostname":"AP-PF1Y22SP","name":"SegmentClient","msg":"using existing id"}
{"level":30,"time":1653312718105,"pid":12732,"hostname":"AP-PF1Y22SP","name":"SegmentClient","msg":"anonymous id","anonymousId":"l0e8eyabj37eg7x2ostjof1"}
{"level":30,"time":1653312718111,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"DendronExtension","msg":"initialized"}
{"level":30,"time":1653312718225,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"_activate","msg":"initializeWorkspace","wsType":"CODE","currentVersion":"0.95.1","previousGlobalVersion":"0.0.0","extensionInstallStatus":"INITIAL_INSTALL"}
{"level":30,"time":1653312718239,"pid":12732,"hostname":"AP-PF1Y22SP","name":"SegmentClient","msg":"user telemetry setting: enabled by config"}
{"level":30,"time":1653312718239,"pid":12732,"hostname":"AP-PF1Y22SP","name":"SegmentClient","msg":"telemetry initializing"}
{"level":30,"time":1653312718239,"pid":12732,"hostname":"AP-PF1Y22SP","name":"SegmentClient","msg":"using existing id"}
{"level":30,"time":1653312718239,"pid":12732,"hostname":"AP-PF1Y22SP","name":"SegmentClient","msg":"anonymous id","anonymousId":"l0e8eyabj37eg7x2ostjof1"}
{"level":30,"time":1653312718239,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","msg":"Telemetry is disabled? false"}
{"level":30,"time":1653312718240,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","msg":"Segment Residual Cache Path is at c:\\Users\\EBromberg\\AppData\\Roaming\\Code\\User\\globalStorage\\dendron.dendron\\segmentresidualcache.log"}
{"level":30,"time":1653312718240,"pid":12732,"hostname":"AP-PF1Y22SP","name":"SegmentClient","msg":"Attempting to flush residual segment data from file."}
{"level":30,"time":1653312718243,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"runMigrationsIfNecessary","changes":[],"workspaceInstallStatus":"NO_CHANGE"}
{"level":30,"time":1653312718250,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"_activate","platform":"win32","extensions":[{"id":"dendron.dendron","version":"0.95.1","active":true},{"id":"dendron.dendron-paste-image","version":"1.1.0","active":false},{"id":"dendron.dendron-markdown-shortcuts"},{"id":"redhat.vscode-yaml","version":"1.7.0","active":false}],"vaults":[{"fsPath":"vault"}]}
{"level":30,"time":1653312718254,"pid":12732,"hostname":"AP-PF1Y22SP","name":"execServer","state":"enter"}
{"level":30,"time":1653312719939,"pid":12732,"hostname":"AP-PF1Y22SP","name":"execServer","state":"post:exec.node"}
{"level":30,"time":1653312720713,"pid":16436,"hostname":"AP-PF1Y22SP","name":"SegmentClient","msg":"No cache path for Segment specified. Failed event uploads will not be retried."}
{"level":30,"time":1653312720713,"pid":16436,"hostname":"AP-PF1Y22SP","name":"SegmentClient","msg":"user telemetry setting: enabled by config"}
{"level":30,"time":1653312720713,"pid":16436,"hostname":"AP-PF1Y22SP","name":"SegmentClient","msg":"telemetry initializing"}
{"level":30,"time":1653312720714,"pid":16436,"hostname":"AP-PF1Y22SP","name":"SegmentClient","msg":"using existing id"}
{"level":30,"time":1653312720714,"pid":16436,"hostname":"AP-PF1Y22SP","name":"SegmentClient","msg":"anonymous id","anonymousId":"l0e8eyabj37eg7x2ostjof1"}
{"level":30,"time":1653312720831,"pid":12732,"hostname":"AP-PF1Y22SP","name":"execServer","state":"message","message":"52492"}
{"level":30,"time":1653312720831,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WSUtils.handleServerProcess","msg":"subprocess running","pid":16436}
{"level":30,"time":1653312720831,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"startServerProcess","msg":"post-start-server","port":52492,"durationStartServer":2601}
{"level":30,"time":1653312720838,"pid":12732,"hostname":"AP-PF1Y22SP","name":"logger","ctx":"FileStorageV2","wsRoot":"c:\\Users\\EBromberg\\Dendron","vaults":[{"fsPath":"vault"}],"level":"info"}
{"level":30,"time":1653312720841,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree: enter"}
{"level":30,"time":1653312720842,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree: exit"}
{"level":30,"time":1653312721905,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"dendron.reloadIndex:run","msg":"pre-execute"}
{"level":30,"time":1653312721906,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"ReloadIndex.execute","msg":"enter"}
{"level":30,"time":1653312721954,"pid":16436,"hostname":"AP-PF1Y22SP","name":"logger","ctx":"parsingSchemas","fname":"root","root":{"fsPath":"vault"},"imports":[]}
{"level":30,"time":1653312722084,"pid":16436,"hostname":"AP-PF1Y22SP","name":"LinkUtils.getLinks","ctx":"getLinks","dlinksLength":0,"noteRefsLength":0,"wikiLinksLength":0}
{"level":30,"time":1653312722107,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"ReloadIndex.execute","durationEngineInit":195}
{"level":30,"time":1653312722107,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"ReloadIndex.execute","msg":"exit"}
{"level":30,"time":1653312722107,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"dendron.reloadIndex:run","msg":"post-execute"}
{"level":30,"time":1653312722123,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"reloadWorkspace","msg":"post-ws.reloadWorkspace"}
{"level":30,"time":1653312722124,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"reloadWorkspace","msg":"exit"}
{"level":30,"time":1653312722133,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"postReloadWorkspace","msg":"same wsVersion"}
{"level":30,"time":1653312722133,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"postReloadWorkspace","msg":"exit"}
{"level":30,"time":1653312722133,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"setupViews","msg":"init:treeViewV2"}
{"level":30,"time":1653312722134,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"setupBacklinkTreeView","msg":"init:backlinks"}
{"level":30,"time":1653312722421,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"activateWorkspace","stage":"prod","msg":"enter"}
{"level":30,"time":1653312722427,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"togglePluginActiveContext","state":"togglePluginActiveContext: true"}
{"level":30,"time":1653312722427,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"_activate","msg":"fin startClient","durationReloadWorkspace":3908}
{"level":50,"time":1653312722434,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","stack":"TypeError: Cannot read properties of undefined (reading 'startsWith')\n\tat c:\\Users\\EBromberg\\.vscode\\extensions\\dendron.dendron-0.95.1\\dist\\extension.js:8:3018886\n\tat forEach (<anonymous>)\n\tat Function.getConflictingKeybindings (c:\\Users\\EBromberg\\.vscode\\extensions\\dendron.dendron-0.95.1\\dist\\extension.js:8:3018860)\n\tat Function.maybePromptKeybindingConflict (c:\\Users\\EBromberg\\.vscode\\extensions\\dendron.dendron-0.95.1\\dist\\extension.js:8:3022039)\n\tat fa (c:\\Users\\EBromberg\\.vscode\\extensions\\dendron.dendron-0.95.1\\dist\\extension.js:8:3222708)\n\tat processTicksAndRejections (node:internal/process/task_queues:96:5)","type":"Error","msg":"Cannot read properties of undefined (reading 'startsWith')"}
{"level":50,"time":1653312722439,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"showInitProgress","msg":"issue initializing Dendron"}
{"level":30,"time":1653312722525,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"updateDecorations","payload":{"error":null,"decorationsLength":2,"diagnosticsLength":0}}
{"level":30,"time":1653312726118,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree: enter"}
{"level":30,"time":1653312726119,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree: exit"}
{"level":30,"time":1653312726128,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"CalendarView:openTextDocument","uri":"extension-output-dendron.dendron-#1","msg":"not in workspace"}
{"level":30,"time":1653312726128,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1653312726989,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"onDidReceiveMessage","data":{"type":"init","data":{"src":"DendronVSCodeApp"},"source":"webClient"}}
{"level":30,"time":1653312726989,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"onDidReceiveMessage","data":{"type":"messageDispatcherReady","data":{},"source":"webClient"}}
{"level":30,"time":1653312737150,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","msg":"sendSavedAnalytics"}
{"level":30,"time":1653312737150,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"AnalyticsUtils.sendSavedAnalytics","message":"start"}
{"level":40,"time":1653312737151,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"AnalyticsUtils.sendSavedAnalytics","msg":"failed to read the saved telemetry dir","telemetryDir":"C:\\Users\\EBromberg\\.dendron\\saved-telemetry"}
{"level":30,"time":1653312747218,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"pre-execute"}
{"level":30,"time":1653312747218,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"execute","opts":{}}
{"level":30,"time":1653312747237,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"post-execute"}
{"level":30,"time":1653312747334,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["extension-output-dendron.dendron-#1"]}
{"level":30,"time":1653312747335,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["extension-output-dendron.dendron-#1","c:\\Users\\EBromberg\\AppData\\Roaming\\Code\\logs\\20220523T092704\\exthost1\\dendron.dendron\\dendron.log"]}
{"level":30,"time":1653312747354,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"CalendarView:openTextDocument","uri":"c:\\Users\\EBromberg\\AppData\\Roaming\\Code\\logs\\20220523T092704\\exthost1\\dendron.dendron\\dendron.log","msg":"not in workspace"}
{"level":30,"time":1653312747354,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1653312747359,"pid":12732,"hostname":"AP-PF1Y22SP","name":"dendron","ctx":"WorkspaceWatcher:onFirstOpen","msg":"enter","fname":"dendron.log"}

**Comment by Harshita-mindfire** [comment] 2022-05-23 15:06
@hikchoi from the logs, it looks like the issue is [here](https://github.com/dendronhq/dendron/blob/master/packages/plugin-core/src/KeybindingUtils.ts#L112:L112)

**Comment by ebromberg** [comment] 2022-05-23 15:56
Does this error prevent any part of Dendron from working?

**Comment by hikchoi** [comment] 2022-05-25 08:01
@ebromberg Sorry about the issue! This seems to happen when we try to detect keybinding conflicts.

If there isn't any sensitive information, can you share what your `keybindings.json` looks like?
This could be accessed by using the command palette and typing `Preferences: Open Keyboard Shortcuts (JSON)`

If you can't share the content of that file, can you confirm that the json file is valid?
Do you have any keybinding rule that doesn't have the required fields (`key` and `command`)?

**Comment by hikchoi** [comment] 2022-05-26 16:56
> What is weird is I don't get the message anymore. Dendron now seems to initialize just fine. I did change some keybindings today so maybe the JSON had an issue but now its correct?

That could be possible. In any case, I think this issue should be gracefully handled on our end. I'll take a look at it.
Feel free to close this issue if the immediate problem on your end is resolved. You can re-open it when you hit the same problem again in the future.

Of course, if you have more related concerns, post it here.

**Comment by kevinslin** [comment] 2022-05-30 23:21
going to close for now. please let us know if this shows up again

**Closed by kevinslin** 2022-05-30 23:21 UTC
Labels: type.bug, scope.workspace
