### ISSUE TITLE
Journal notes frontmatter differs between lookup and new daily note

### ISSUE THREAD

**Issue by Bassmann** [dendronhq/dendron#2341] opened 2022-02-02 19:35 UTC
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [X] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

There is a difference in the frontmatter for a journal note depending on how it is created
- using the new journal command (ctrl+shift+j) adds the full date as title as well as adding a trait entry
- creating it using lookup doesn't add the trait and also just adds the day as title

## To Reproduce

- Initialize a new workspace
- Create a new daily journal note. I tested both with the shortcut ctrl-shift-i and with the command Create Daily Journal Note, This creates a new daily note with this frontmatter
```
id: nxLJRRvAYJh5dX2mtmj7Y
title: '2022-02-01'
desc: ''
updated: 1643744888344
created: 1643744888344
traitIds:
  - journalNote
```
- Then do a lookup for daily.journal.2022.02.02 and create a new note.
This creates a note with this frontmatter
```
id: 7IHhHk1fLk8PITfCzD4BG
title: '02'
desc: ''
updated: 1643744647012
created: 1643744647012
```
And interestingly if I use Ctrl-Shift-j to create a note it has this frontmatter
```
id: UUDvruacLmkg1ojRhUNYT
title: '2022-02-01'
desc: ''
updated: 1643745128268
created: 1643745128268
```
i.e. without the traitsId

## Expected behavior

The frontmatter should be the same independent of how the note is created. In particular the title should be the full date 
## Desktop (please complete the following information)

- OS: Windows and Mac
- Version: 0.79

**Comment by aleksey-rowan** [comment] 2022-02-03 02:45
#2242 is tangentially related to this as it asks for functionality to create daily notes for future dates and these notes should also use the proper frontmatter (the full date as the title in particular).

**Comment by ScriptAutomate** [comment] 2022-02-03 03:27
Potential duplicate of https://github.com/dendronhq/dendron/issues/2211

**Comment by Bassmann** [comment] 2022-02-03 06:26
#2211 is mostly the same but beside the traitsId also the title is different depending on the creation method. 

#2242 talks about new commands to create future notes. I'm happy with selecting them manually. Haven't tried the calendar view in a while since it only supported the standard hierarchy `daily.journal.*` whereas I just use `journal`.

**Comment by Harshita-mindfire** [comment] 2022-02-03 08:06
Thanks @Bassmann for reporting the issue! The daily journal created via lookup is not treated as a special note hence the title is different.
Keeping this open since it coincides #2211 and has an additional case of creating note via `Ctrl-Shift-j`
Pinging @jonathanyeung for visiblity

**Comment by jonathanyeung** [comment] 2022-02-07 14:37
Thanks @Bassmann for the issue - I'll take a look at this one in the following sprint.

**Comment by jonathanyeung** [comment] 2022-03-08 10:19
A fix for this went out with v83.  

Some notes from the PR: 

---

After this change, when creating a Journal note from the following scenarios below should result in consistent frontmatter

Dendron: Create Daily Journal Note
Dendron: Create Journal Note
Creating a note via Lookup with the Journal button selected
Clicking on a new date in the Calendar webview
Frontmatter should look like

```yaml
---
id: IRbGt7WJKEsHNOcfYE2lS
title: '2022-02-11'
desc: ''
updated: 1644575670992
created: 1644575670993
traitIds:
  - journalNote
---
```
NOTE: By design (for now), if you create a new note via lookup with a title like daily.journal.2022.01.01 without the journal modifier button clicked - basically you typed in the note name manually - then the title and traitIds will not be applied. We may look to modify this behavior as we re-examine how some of the button behavior works in Lookup, but that's out of scope in this change.

--- 

@Bassmann  - can you let us know if you think this fixes the issue in a satisfactory manner for now?

**Closed** 2022-03-11 10:33 UTC
Labels: type.bug, status.info-needed, scope.lookup
