### ISSUE TITLE
Updated field not updating when body text is changed and file is saved

### ISSUE THREAD

**Issue by apastuszak** [dendronhq/dendron#967] opened 2021-07-13 14:05 UTC
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [X] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [X] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

When I update a note and save it the updated field never get updated.

## To Reproduce

1. Create a new note or open an existing note
2. Make a change to it
3. Save the note
4. See that the updated: field has not changed.

## Expected behavior

I expect the updated field to update to the current date and time.

## Desktop (please complete the following information)

- OS: Windows 10 64-bit and MacOS Catalina Intel
- Browser n/a
- Version Dendron versions 0.49 and 0.50

## Dendron Log file

[dendron.log](https://github.com/dendronhq/dendron/files/6809447/dendron.log)

```

**Comment by kevinslin** [comment] 2021-07-13 15:07
This is a regression on our end. Will be fixed in 0.51!

**Comment by kevinslin** [comment] 2021-07-28 20:56
this should be fixed in v52 of Dendron. please post here if not, otherwise this issue will auto close in 3 days

**Closed** 2021-08-03 00:26 UTC
Labels: area.create, area.structure, status.info-needed, type.bug

**Comment by bonnebulle** [comment] 2023-01-07 10:22
Same here...
When "Auto-saving" is Off ... ( workbench.action.toggleAutoSave ) date/time is not updated on save.
I disabled it because, when On, I cant undo my text writing (because the front matter is updating the current time/date)
Have you any option/clue to help me ? 
How to exclude front matter from undo history ?
Maybe ... I dont know  
Thanks for all your work
