### ISSUE TITLE
Dendron Tree widget not updating on new note creation (regression)

### ISSUE THREAD

**Issue by lukors** [dendronhq/dendron#1430] opened 2021-09-27 20:22 UTC
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

Creating a new note does not update the tree view.

## To Reproduce

1. Create a new note
2. Look in the tree view

## Expected behavior

The new note should appear in the tree view.

## Desktop (please complete the following information)

- OS: Pop!_OS 21.04 (Ubuntu)
- Dendron version: v0.60.1

## Additional context

This bug was fixed before: #670

## Dendron Log file

[dendron.log](https://github.com/dendronhq/dendron/files/7239085/dendron.log)

**Comment by hikchoi** [comment] 2021-09-28 01:33
Thank you for the report. I apologize for the inconvenience. We'll look into what's causing this issue.

Pinging @nickolay-kondratyev for potential cache issue

**Comment by shanest** [comment] 2021-12-29 20:56
Having the same issue on macOS Big Sur with dendron v0.75.0

**Comment by aleksey-rowan** [comment] 2022-07-01 02:21
Hey, @lukors and @shanest, there have been some changes to the tree view since v0.75 (and the V2 Tree view has been dropped entirely). Could you please confirm that you are still having an issue with the tree not updating on note creation? Thank you.

**Comment by kevinslin** [comment] 2022-07-04 15:53
don't think this is an issue anymore. feel free to comment here if otherwise, otherwise, this issue will autoclose in a few days

**Comment by lukors** [comment] 2022-07-04 20:38
Sure @aleksey-rowan! I think the issue is that I'm not the target audience. Dendron has too much functionality for my purposes, so its complexity didn't come with enough benefits.

I've since switched to Apple Notes, and it covers my needs while being much simpler and available both on PC and mobile. Dendron just wasn't for me. :)

**Comment by aleksey-rowan** [comment] 2022-07-13 13:28
@lukors, thank you for sharing your perspective. Regardless of the note app you use, I hope it works well for your needs!

I'm going to close this issue as unreproducible.

**Closed by aleksey-rowan** 2022-07-13 13:28 UTC
Labels: type.bug, area.create
