### ISSUE TITLE
Note preview background color is not applied correctly

### ISSUE THREAD

**Issue by hikchoi** [dendronhq/dendron#3453] opened 2022-08-26 03:43 UTC
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [x] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug
If the rendered note preview is smaller than the editor tab size, the applied background color of the note preview only extends to the end of the rendered body.

## To Reproduce

1. Open a note
2. Toggle preview on
3. Resize note preview tab so that the rendered content is smaller than the editor size
4. Notice the background color is not applied all the way down

## Expected behavior
Background color is applied to the entire webview container

## Screenshots

![image](https://user-images.githubusercontent.com/1219789/186812914-407de977-4b3d-467d-86a1-9e6a923a2164.png)

## Desktop (please complete the following information)

- Browser (if with published websites; include version): [e.g. chrome, safari]
- Versions (all that apply to bug):
  - Dendron Extension: 0.109.1
  - VS Code version: 1.71.0-insiders
  - Dendron CLI:

## Dendron Log file

Please attach the output of `> Dendron:Dev: Open Logs` here

**Comment by namjul** [comment] 2022-09-14 12:58
I am not able to reproduce this on the current master. @hikchoi can you check again on your end?

**Comment by hikchoi** [comment] 2022-09-15 10:54
I'm still seeing this in v112. Let me check if I can repro on master and get back to you. Maybe this is not an issue if you use the default theme?

**Comment by hikchoi** [comment] 2022-09-15 11:13
Weird. If I build master and test it out I can't repro it but it's still an issue if I try it with the published extension. I don't think it's a bundling issue because I don't see any errors related to css not being found.

Adding a screenshot of inspect hoping it helps:
<img width="819" alt="Screen Shot 2022-09-15 at 8 11 20 PM" src="https://user-images.githubusercontent.com/1219789/190389475-817076c2-c17d-4848-87e2-91f23a38db4f.png">

The background-color is only applied to the div `main-content-wrap`, which at times does not extend all the way down to fill up the body

**Comment by namjul** [comment] 2022-09-16 12:40
@hikchoi found the cause. if you set `preview.theme` to a value you get this contrast in the background. Which gets applied in https://github.com/dendronhq/dendron/blob/af339f06ea189cba683448d3a3abd1c667ace683/packages/plugin-core/src/views/utils.ts#L147 gets applied (funny thing is if `defaultInitialTheme` does not get applied if its an empty string which is good because we otherwise get this background failure all the time but the default implies it should get applied). Which further has the effect of down the line of theme styles being prepended instead of appended which then causes this https://github.com/dendronhq/dendron/blob/af339f06ea189cba683448d3a3abd1c667ace683/packages/common-server/src/etc.ts#L127-L131

**Comment by kevinslin** [comment] 2022-09-16 13:10
nice find! do we have a fix for this?

**Comment by namjul** [comment] 2022-09-17 13:51
> nice find! do we have a fix for this?

yes, working on it.

**Comment by hikchoi** [comment] 2022-09-20 02:23
nice! I can confirm that removing `initialTheme` resolves the issue on my end.

**Closed** 2022-09-20 15:11 UTC
Labels: type.bug, scope.views
