### ISSUE TITLE
[Dendron Paste Image] Purge command to remove orphaned images (no backlinks)

### ISSUE THREAD

**Issue by teauxfu** [dendronhq/dendron#900] opened 2021-06-30 17:36 UTC
## Please Select if your Request is Either something new or an Enhancement ##

- [ ] Enhancement of an existing Feature.
- [x] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible) ##

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [x] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)

## Is your feature request related to a problem? Please describe ##

the `/assets/images` folder of a vault can become bloated over time

### example workflow
1. you are prototyping something and discussing your thoughts in a note
2. you paste in some images of possible options for your design

```md
# option 1
![](assets/2021-06-30-10-05-26.png)

# option 2
![](assets/2021-06-30-11-22-34.png)
```

3. later, you decide to scrap option 2, so you delete it from the note

now `2021-06-30-11-22-34.png`  is orphaned in the `/assets/images` folder 

this is probably undesirable for most users, and there's not an obvious way to filter the files there by which ones are referenced elsewhere and which are not (afaik). this could lead to clutter and bloat

## Describe the solution you'd like ##

A command like `> Purge vault assets` that would work something like
1. iterate over matching files in the particular dir eg. `/assets/images/*.png`
2. if the file has no backlinks, add it to a list `deleteme`
3. show user an action preview similar to the one used for refactoring notes
4. if they user `proceed`s, delete all the files in `deleteme` else pass

## Describe alternatives you've considered ##

Manually deleting old images is an option for my use case (since I have only a few dozen notes), albeit cumbersome and would scale poorly for large volumes of notes. 

Because the file names are rather long and auto-generated (a sane default) it's kind of awkward to search for them from `ctrl+P` searches, and you can't navigate to them directly from within Dendron (afaik)

You could use VSCode's `ctrl+shift+F` search feature to look for the text of the filename within notes, then delete the image file if you get no hits, but this would also scale poorly for operating on a large number of images

**Comment by kpathakota** [comment] 2021-07-06 12:33
Closing as a duplicate of #650

**Closed by kpathakota** 2021-07-06 12:33 UTC
Labels: area.misc, area.retrieve, status.duplicate, type.feature
