### ISSUE TITLE
Note preview panel does not scroll with the note

### ISSUE THREAD

**Issue by ric03uec** [dendronhq/dendron#2911] opened 2022-05-11 23:21 UTC
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  DendroScrolling in the note preview does not n Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [x] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

When scrolling through the note, the markdown preview on the right panel does not scroll automatically. 

## To Reproduce

1. open a note
2. write a bunch of stuff so that it fills multiple pages
3. check the right side markdown panel. this stays on the first page (top of the note)

## Expected behavior

The markdown panel on the right should scroll with the note

## Screenshots

![image](https://user-images.githubusercontent.com/1110988/167963036-96b3eb96-5a1c-4fa9-90da-ad8c3fcb3ec4.png)

## Desktop (please complete the following information)

Versions (all that apply to bug):

    Dendron Extension: v0.93.0
    VS Code version: 1.66.2
    Dendron CLI: 0.93.0
    Chromium: 98.0.4758.109
    Node.js: 16.13.0
    V8: 9.8.177.11-electron.0
    OS: Linux x64 5.4.0-109-generic

## Additional context

NA

**Comment by jonathanyeung** [comment] 2022-05-12 02:31
Thanks @ric03uec for filing.  This feature isn't implemented yet in our Preview. 

This is a duplicate of https://github.com/dendronhq/dendron/issues/1978

**Comment by aleksey-rowan** [comment] 2022-05-22 18:03
Closing as a duplicate of

- https://github.com/dendronhq/dendron/issues/1978

**Closed by aleksey-rowan** 2022-05-22 18:03 UTC
Labels: scope.markdown
