### ISSUE TITLE
Rename Note removes it from Tree View

### ISSUE THREAD

**Issue by sidwellr** [dendronhq/dendron#763] opened 2021-05-26 02:30 UTC
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [X] Misc (Choose this if your not sure)

## Describe the bug

Using Dendron: Rename Note correctly renames the note, but the renamed note no longer appears in Tree View. (Restarting VSCodium makes it reappear.)

## To Reproduce

1. Go to some note; note that it appears in Tree View
2. Click F1 (or Ctrl-Shift-P) and choose Dendron: Rename Note
3. Enter a new name
4. The note is renamed, but neither the old nor the new name now appears in Tree View

## Expected behavior

Tree View should have been updated with the new name.

## Desktop (please complete the following information)

- OS: Windows 10 Home version 20H2
- VSCodium 1.56.2
- Dendron 0.43

## Dendron Log file

Please attach the output of `>Dev:Dendron: Open Logs` here

Couldn't find >Dev:Dendron:Open Logs; "No matching commands"

**Comment by aleksey-rowan** [comment] 2022-04-12 00:41
This seems to have been fixed and the note is no longer removed from the tree view, but if the note had a schema icon, the icon disappears. I suppose it should be spun off into a separate issue.

**Comment by aleksey-rowan** [comment] 2022-05-04 18:59
@sidwellr Could you please check if it's still a problem for you with the latest version?

**Comment by hikchoi** [comment] 2022-06-08 07:47
We did a round of fixes to the tree view and I am now unable to reproduce this.

I'll close this for now, but please re-open or create a new issue if a similar issue arises.

**Closed by hikchoi** 2022-06-08 07:47 UTC
Labels: type.bug, status.help-wanted, area.misc, status.info-needed
