### ISSUE TITLE
Dendron fails to render mermaid diagrams when angled <<>> brackets are used

### ISSUE THREAD

**Issue by henry-js** [dendronhq/dendron#2630] opened 2022-03-24 20:16 UTC
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [X] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Mermaid class diagrams should be able to annotate classes by placing the type inside double angled brackets `<<>>`. If attempted in Dendron, Note Preview states there is a "Syntax error in graph". Deactivating Dendron and installing [Markdown Preview Mermaid Support](https://github.com/mjbvz/vscode-markdown-mermaid) renders properly.

## To Reproduce

1. Go to any note
2. Create a mermaid class diagram such as:
```mermaid
classDiagram
    Animal <|-- Duck
    Animal <|-- Fish
    Animal <|-- Zebra
    Animal : +int age
    Animal : +String gender
    Animal: +isMammal()
    Animal: +mate()
    class Duck{
        <<interface>>
      +String beakColor
      +swim()
      +quack()
    }
    class Fish{
        <<enum>>
      -int sizeInFeet
      -canEat()
    }
    class Zebra{
        <<struct>>
      +bool is_wild
      +run()
    }
```
4. Click "Dendron: Show Preview"
5. See error

## Expected behavior

Should render mermaid diagram properly.

## Screenshots
Using Dendron:
![image](https://user-images.githubusercontent.com/79054685/160001596-21651567-628e-480d-a868-66182b048cc3.png)

Using Markdown Preview Mermaid Support:
![image](https://user-images.githubusercontent.com/79054685/160001780-d5f1b132-9c5d-4e07-a5d7-74b72f85eca9.png)

## Desktop (please complete the following information)

- OS: Win11 21H2
- Browser (if with published websites; include version): [e.g. chrome, safari]
- Versions (all that apply to bug):
  - Dendron Extension: 0.87.0
  - VS Code version: 1.66.0-insider
  - Dendron CLI:

**Comment by SeriousBug** [comment] 2022-03-25 18:28
Thanks for the report! I think this is caused by Dendron's mermaid extension being a bit outdated. We'll make sure to update and it let you know when a Dendron version with the update is out.

**Comment by SeriousBug** [comment] 2022-04-05 18:50
This should be fixed in Dendron 0.89. Please let us know if it doesn't work for you after updating and restarting.

**Comment by SeriousBug** [comment] 2022-04-21 20:51
Thanks, I can reproduce the issue. I'll make sure to look into this further.

**Comment by SeriousBug** [comment] 2022-05-17 08:08
I identified the issue and I'm working on a fix. In the meantime, you can work around this by escaping the `<` and `>` characters like this:

```
    &lt;&lt;interface&gt;&gt;
```

**Comment by SeriousBug** [comment] 2022-06-08 05:48
This should now be fixed, please let us know if you continue to have issues after updating to the latest version.

**Closed** 2022-06-09 05:11 UTC
Labels: type.bug, status.info-needed, scope.views
