### ISSUE TITLE
As a user I want to have git auto-commit mechanism

### ISSUE THREAD

**Issue by xmailla** [dendronhq/dendron#3356] opened 2022-08-06 22:20 UTC
## Please select if your request is either something new or an enhancement ##

- [ ] Enhancement of an existing Feature.
- [X] Request of a new feature.

## Please select the area your request applies to. (Multiple selections are Possible. You can leave blank if you're not sure.) ##

- [X] Workspace - VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup - Dendron's Lookup Command
- [ ] Views - Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema - Dendron Schemas
- [ ] Pod - Data import from / export to Dendron
- [ ] Publish - External Site Publish
- [ ] Markdown - Markdown features, such as syntax support and features

## Is your feature request related to a problem? Please describe ##

I am not pleased with 3rd party syncing option like OneDrive&friend. I'd rather want to use Git for that. Problem ? I have to manually add files, commit files and push my changes right into my GitHub repo.

I'd rather want this to kind of auto-magic; I could indicate I am using git in my settings and it should play alone using Github API calls or something like that. Just like Logseq did.

## Describe alternatives you've considered ##

Manually doing this boring stuff from VS.

**Comment by rlh1994** [comment] 2022-08-07 16:28
Would you be open to using another extension to do this? There's one called runOnSave that you could use and this would then work for any repo not just dendron workspaces? https://stackoverflow.com/a/71551141

**Comment by rlh1994** [comment] 2022-08-07 16:30
Possible duplicate of #3262

**Comment by kevinslin** [comment] 2022-08-08 01:35
@rlh1994 is correct about this being a duplicate - closing in favor of #3262 . could you please upvote with 👍 to help us prioritize?

**Closed by kevinslin** 2022-08-08 01:35 UTC
Labels: type.feature, status.triage-needed, scope.workspace
