### ISSUE TITLE
Tags shown same as document title

### ISSUE THREAD

**Issue by singlebunglemrbungle** [dendronhq/dendron#790] opened 2021-06-04 02:53 UTC
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [X] Misc (Choose this if your not sure)

## Describe the bug

[[tag.nonex]] or [[tag.ex]] is shown as intended. (nonex as non-existing, ex as existing)
However, tags made from pressing # + tab `[[#nonex|tag.nonex]] [[#ex|tag.ex]]` are shown same as 'file metadata title'.

## To Reproduce

1. Open any .md file in the vault
2. Open dendron enhanced preview
3.  [[tag.nonex]] or [[tag.ex]] is shown as intended.
4. Tags made from pressing # + tab `[[#nonex|tag.nonex]] [[#ex|tag.ex]]` are shown same as 'file metadata title'.

## Expected behavior

Tags should be shown as intended in Dendron technical documents.

## Screenshots

![list](https://user-images.githubusercontent.com/84944869/120736297-ff71a880-c526-11eb-98c2-938dec3096ae.JPG)

## Desktop (please complete the following information)

- OS: Windows 10 20H2 (19042.985)
- Browser: Firefox
- Version: Dendron 0.44.0

## Additional context

When I type
`> config (Dendron: Configure)`

It displays anything but white blank page.
![image](https://user-images.githubusercontent.com/84944869/120749292-4ec3d300-c53f-11eb-9e8c-665685684b33.png)

When you change the title of the document in metadata section(top of the text), tags in question(`[[#nonex|tag.nonex]] [[#ex|tag.ex]]`)
 *  shows same as the title
*   or ***takes time to show changed title***

 to resolve the problem I did:
* disabling Todo Tree:  doesn't matter
* disabling/uninstalling Dendron Preview Enhanced: doesn't matter
* making additional vault in the same workspace: same bug happened
* making new workspace and its default vault: same bug happened

things done before but then worked fine, seems not relevant:
* added just one font in enhanced preview CSS.
* added one daily journal schema yml. [daily.schema.yml.txt](https://github.com/dendronhq/dendron/files/6595448/daily.schema.yml.txt)
* reload dendron/webview/etc.

things irregular, usually disappeared:
* by shutdown and relaunch the vscode
failed initializing
* It sometimes does not work(just ignore snippetting?) "# + tab autocompletion tag". Relaunching the vscode, it works as intended

## Dendron Log file

Please attach the output of `>Dev:Dendron: Open Logs` here

[dendron.log](https://github.com/dendronhq/dendron/files/6595345/dendron.log)

**Comment by kpathakota** [comment] 2021-06-04 10:04
Yup, this looks like a regression. We should fix this asap. Pretty tags should work as described here: https://wiki.dendron.so/notes/8bc9b3f1-8508-4d3a-a2de-be9f12ef1821.html

**Comment by kpathakota** [comment] 2021-06-04 10:10
@all-contributors please add @singlebunglemrbungle for bug

**Comment by singlebunglemrbungle** [comment] 2021-06-06 12:01
I feel honored to have a seat in the prestigious place on the main page(I mean, literally). Now I know why gamers love to get achievements.

**Comment by af4jm** [comment] 2021-06-07 17:31
I just hit the same thing `[[#in progress|tag.in_progress]]`... if I remove the leading # `[[in progress|tag.in_progress]]` it works as expected

seems the bug is that if the first character is `#` it doesn't check if the `|` is there

**Comment by SeriousBug** [comment] 2021-06-07 17:55
Thanks for the reports, I am able to reproduce the problem, and I'm working to fix it now.

**Comment by kevinslin** [comment] 2021-06-17 17:17
this is fixed with 0.46 release

**Closed by kevinslin** 2021-06-17 17:17 UTC
Labels: area.misc, type.bug
