### ISSUE TITLE
Cannot read properties of undefined (reading 'fname')

### ISSUE THREAD

**Issue by mysoonyu** [dendronhq/dendron#2786] opened 2022-04-19 13:11 UTC
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [x ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug
1. when open workspace, tree view is blank. 
2. cannot read properties of undefined (reading 'fname')

cant view the file from tree as normal.

## To Reproduce

1. from visual code, remote connect to vagrant ubuntu server
2. file workspace from file
3. dendron is active
4. click on tree view -> cannot read properties of undefined (reading 'fname')

## Expected behavior
file should list in tree view

## Screenshots
![image](https://user-images.githubusercontent.com/64881900/164011168-42776c96-aace-4f5b-9df8-fc5da8c05e99.png)
![image](https://user-images.githubusercontent.com/64881900/164011198-6cfa93ac-2ae3-4511-bd7a-d9c53a78e1c7.png)

## Desktop (please complete the following information)

- Browser (if with published websites; include version): [e.g. chrome, safari]
- Versions (all that apply to bug):
  - Dendron Extension:
  - VS Code version: 1.66.2
  - Dendron CLI: 
  - Dendron version :0.86.0

## Dendron Log file

Please attach the output of `> Dendron:Dev: Open Logs` here
[dendronlog1.txt](https://github.com/dendronhq/dendron/files/8513224/dendronlog1.txt)

**Comment by mysoonyu** [comment] 2022-04-19 14:49
reinstall dendron and still same issue facing

**Comment by kevinslin** [comment] 2022-04-21 16:24
hmm, i'm unable to reproduce this on the latest version of dendron (0.91). i'm using https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh

is this your setup? if so, can you try running "Launch Tutorial" and see if tree view works on a brand new workspace? this will help us isolate if its an issue with dendron or your workspace

**Comment by mysoonyu** [comment] 2022-04-22 03:48
1. install dendron from visual code extention. currently show last update as 19/4/2022 exactly the time i start hit issue
![dendronextention](https://user-images.githubusercontent.com/64881900/164592257-410d7bd0-bad8-498e-bae6-03ee381063bd.PNG)
2. launch tutorial no issue
![dendrontutorial](https://user-images.githubusercontent.com/64881900/164592468-cc9496d8-87d2-4146-b2ba-731096cbea3d.PNG)

**Comment by mysoonyu** [comment] 2022-04-22 05:00
I initial a new workspace from visual code. copy all the dendron file from old workspace to new workspace and error gone away..

**Comment by aleksey-rowan** [comment] 2022-04-25 18:41
Hey, @mysoonyu. Looks like this issue has been reported before:

- https://github.com/dendronhq/dendron/issues/2534

If the linked issue does describe your problem, would you be okay with closing this one and commenting on/upvoting the other one?

**Comment by SeriousBug** [comment] 2022-04-27 07:54
I just got this error too, and managed to get the full error message from the developer tools:

```
notificationsAlerts.ts:40 TypeError: Cannot read properties of undefined (reading 'fname')
	at /home/kaan/.vscode/extensions/dendron.nightly-0.91.2/dist/extension.js:2:149318
	at Array.find (<anonymous>)
	at Function.l.sortNotesAtLevel (/home/kaan/.vscode/extensions/dendron.nightly-0.91.2/dist/extension.js:2:149304)
	at qi.parseTree (/home/kaan/.vscode/extensions/dendron.nightly-0.91.2/dist/extension.js:8:3220078)
	at /home/kaan/.vscode/extensions/dendron.nightly-0.91.2/dist/extension.js:8:3220454
	at Array.map (<anonymous>)
	at qi.parseTree (/home/kaan/.vscode/extensions/dendron.nightly-0.91.2/dist/extension.js:8:3220166)
	at /home/kaan/.vscode/extensions/dendron.nightly-0.91.2/dist/extension.js:8:3220454
	at Array.map (<anonymous>)
	at qi.parseTree (/home/kaan/.vscode/extensions/dendron.nightly-0.91.2/dist/extension.js:8:3220166)
	at /home/kaan/.vscode/extensions/dendron.nightly-0.91.2/dist/extension.js:8:3220454
	at Array.map (<anonymous>)
	at qi.parseTree (/home/kaan/.vscode/extensions/dendron.nightly-0.91.2/dist/extension.js:8:3220166)
	at /home/kaan/.vscode/extensions/dendron.nightly-0.91.2/dist/extension.js:8:3219364
	at Array.flatMap (<anonymous>)
	at qi.getChildren (/home/kaan/.vscode/extensions/dendron.nightly-0.91.2/dist/extension.js:8:3219334)
	at _.fetchChildrenNodes (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:19383)
	at _.getChildren (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:15769)
	at v.$getChildren (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:11860)
	at i._doInvokeHandler (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:13826)
	at i._invokeHandler (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:13510)
	at i._receiveRequest (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:12171)
	at i._receiveOneMessage (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:11044)
	at /opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:8947
	at u.invoke (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at v.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
	at d.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:19034)
	at /opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:34275
	at u.invoke (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at v.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
	at d.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:19034)
	at o._receiveMessage (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:23615)
	at /opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:21149
	at u.invoke (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at v.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
	at v.acceptChunk (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:15865)
	at /opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:14995
	at Socket.P (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:13797)
	at Socket.emit (node:events:390:28)
	at Socket.emit (node:domain:475:12)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
onDidChangeNotification @ notificationsAlerts.ts:40
```

@hikchoi Could you take a look at this? Sorry I don't have more available on how to repro

**Comment by hikchoi** [comment] 2022-04-27 08:21
Thanks for the reports @mysoonyu and @SeriousBug. I'll take a look at this.

**Comment by bpathakota** [comment] 2022-05-30 05:47
[error-fname.txt](https://github.com/dendronhq/dendron/files/8795762/error-fname.txt)
Got the same error - attached logs.

**Comment by SeriousBug** [comment] 2022-05-31 18:35
@hikchoi Got another stack trace, I think this is a bit more informative than the last one I managed to get:

```
notificationsAlerts.ts:40 TypeError: Cannot read properties of undefined (reading 'fname')
	at /home/kaan/.vscode/extensions/dendron.nightly-0.96.6/dist/extension.js:2:208796
	at Array.find (<anonymous>)
	at Function.d.sortNotesAtLevel (/home/kaan/.vscode/extensions/dendron.nightly-0.96.6/dist/extension.js:2:208782)
	at ia.parseTree (/home/kaan/.vscode/extensions/dendron.nightly-0.96.6/dist/extension.js:8:3339207)
	at /home/kaan/.vscode/extensions/dendron.nightly-0.96.6/dist/extension.js:8:3339595
	at Array.map (<anonymous>)
	at ia.parseTree (/home/kaan/.vscode/extensions/dendron.nightly-0.96.6/dist/extension.js:8:3339307)
	at /home/kaan/.vscode/extensions/dendron.nightly-0.96.6/dist/extension.js:8:3339595
	at Array.map (<anonymous>)
	at ia.parseTree (/home/kaan/.vscode/extensions/dendron.nightly-0.96.6/dist/extension.js:8:3339307)
	at /home/kaan/.vscode/extensions/dendron.nightly-0.96.6/dist/extension.js:8:3338234
	at Array.flatMap (<anonymous>)
	at ia.getChildren (/home/kaan/.vscode/extensions/dendron.nightly-0.96.6/dist/extension.js:8:3338204)
	at E.fetchChildrenNodes (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:19703)
	at E.getChildren (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:15909)
	at g.$getChildren (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:12000)
	at s._doInvokeHandler (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:86:13828)
	at s._invokeHandler (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:86:13512)
	at s._receiveRequest (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:86:12173)
	at s._receiveOneMessage (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:86:11046)
	...
```

Looks like it's happening inside `sortNotesAtLevel`.

**Closed** 2022-06-09 05:11 UTC
Labels: type.bug, status.info-needed, scope.workspace
