### ISSUE TITLE
Links do not render in V2 when following a checkbox-like element

### ISSUE THREAD

**Issue by aleksey-rowan** [dendronhq/dendron#1229] opened 2021-08-29 01:40 UTC
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)

## Describe the bug

A wiki links fails to render in V2 preview if it's following a checkbox-like element (a pair of square brackets enclosing something other than `x` or ` `, or missing a dash):

```md
- [ ] [[test]]
- [x] [[test]]
- [y] [[test]]
- [1] [[test]]
- [~] [[test]]

[ ] [[test]]

[x] [[test]]

[y] [[test]]

[1] [[test]]

[~] [[test]]

[] [[test]]
```

The above produces this:

![image](https://user-images.githubusercontent.com/79934725/131235377-02eddab8-595f-4dfd-afa5-fbab8ff9cd3a.png)

## To Reproduce

1. Copy the above md
2. Preview
3. Observes that links are not rendered properly in all cases.

## Expected behavior

Wiki links should render properly.

## Desktop (please complete the following information)

- Version 0.56

**Comment by SeriousBug** [comment] 2021-08-29 05:31
Hi! Thanks for reporting this issue, I believe this is a duplicate of issue #1016. This requires some significant changes on our end, but I'll try to work on this as soon as possible.

**Closed** 2021-08-29 05:32 UTC
Labels: type.bug, area.misc, status.duplicate

**Comment by aleksey-rowan** [comment] 2021-08-29 12:12
Yes, it does seem like a duplicate. Apologies, I didn't see that issue.
