### ISSUE TITLE
extension can't be installed under OniVim2 editor

### ISSUE THREAD

**Issue by gour** [dendronhq/dendron#540] opened 2021-03-14 13:28 UTC
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [ ] Hierarchy
- [ ] Graph
- [X ] Misc (Choose this if your not sure)

## Describe the bug

I know that OniVim2 editor is not listed as comptible one, but it does support VSCode extensions and I have problem installing it - see [this](https://github.com/onivim/oni2/issues/3268) issue!

Anything that can be done at Dendron's side?

Sincerely,
Gour

**Comment by kpathakota** [comment] 2021-05-24 10:31
I think this is a duplicate of #41 (I followed the onivim side issue it seems that Dendron needs to be installed without a workspace file dependency for this to work). 

That said, we're all super interested in getting OniVim2 to work so once full extension support is completed (https://github.com/onivim/oni2/issues/3128) we can tackle this one. Closing as duplicate.

**Closed by kpathakota** 2021-05-24 10:31 UTC
Labels: area.misc, status.duplicate, type.bug
