### ISSUE TITLE
Left navigation tree overlaps content if scrolled horizontally for published site

### ISSUE THREAD

**Issue by taranlu-houzz** [dendronhq/dendron#2960] opened 2022-05-23 22:09 UTC
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [x] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

In some cases, when viewing the published site on a vertical screen (e.g. monitor turned 90°) the content is too long horizontally and needs to be scrolled. When scrolled to the left, the content overlaps with navigation tree on the left.

It is unclear to me how it decides to wrap the content... For some of my notes, it seems to be adaptive to the screen size, while for others, it choses not to wrap, which is where I run into this horizontal scrolling issue.

## To Reproduce

1. Publish content to a GitHub pages site as suggested here: https://wiki.dendron.so/notes/FnK2ws6w1uaS1YzBUY3BR/#next-steps
2. View the published site on screen with a vertical aspect ratio (seems to depend on the content for some reason...

## Expected behavior

The scrolled content should draw either completely under or over the navigation tree (under is probably better).

It would also be nice to be able to collapse the navigation tree so that it does not interfere with the content at all (e.g. maybe to a hamburger menu in the top left?).

## Screenshots

<img width="1071" alt="Screen Shot 2022-05-23 at 15 04 54" src="https://user-images.githubusercontent.com/52425255/169912933-0f159ba8-9d31-4e75-9dde-dd9752847e8d.png">

## Desktop (please complete the following information)

- OS: macOS
- Browser (if with published websites; include version): Chrome Version 101.0.4951.64 (Official Build) (x86_64)
- Versions (all that apply to bug):
  - Dendron Extension: v0.95.1
  - VS Code version: 1.67.2
  - Dendron CLI: 0.87.0

**Comment by Harshita-mindfire** [comment] 2022-05-24 05:12
Thanks @taranlu-houzz for raising the issue. This is a duplicate of https://github.com/dendronhq/dendron/issues/2407

**Closed** 2022-05-24 05:12 UTC
Labels: type.bug, scope.publish, status.duplicate
