### ISSUE TITLE
Markdown list UX improvements

### ISSUE THREAD

**Issue by tmladek** [dendronhq/dendron#401] opened 2020-12-11 17:09 UTC
**Is your feature request related to a problem? Please describe.**
_I'm always frustrated_ when I press "Enter" in a markdown list, and it just makes a line-break, instead of adding a new item (i.e. starting a new line with ` - ` or whatever the list marker happens to be).

Similarly, Tabbing and Shift+Tabbing to change indentation levels would be really neat.

**Describe the solution you'd like**
To press enter and get a new list item.

**Describe alternatives you've considered**
I checked VS Code Markdown settings, and curiously there's nothing like it. I also tried installing [Markdown All In One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one) but for some reason, it often gets into a state where each press of a Backspace or an Enter results in a several-second long hang, which is unusable.

**Additional context**
I'm not 100% sure if this should be a Dendron feature - after all, Markdown lists aren't just specific to Dendron, but I asked on the Discord, and Kevin told me to post a feature request because it comes up often in Dendron circles, so here it is :)

**Comment by aleksey-rowan** [comment] 2022-02-15 02:59
Doesn't tabbing/shift+tabbing change indentation anyway? I know it's only when the cursor is at the start of the line, but it's working.

With the markdown lists, if you don't use an extension, mapping `Shift + Enter` to add a new line with a dash could be a workaround:

```md
    // keybindings.json
    // auto bullet list
    // https://wiki.dendron.so/notes/692fa114-f798-467f-a0b9-3cccc327aa6f/#auto-bullet-list
    {
        "key": "shift+enter",
        "command": "type",
        "args": {
            "text": "\r\n- "
        },
        "when": "editorTextFocus && !editorReadOnly && editorLangId == 'markdown'"
    }
```

**Comment by aleksey-rowan** [comment] 2022-03-04 19:04
Hey, @tmladek, I'm going to close this as a duplicate of

- #2423

I realize this is an older issue, but the other one is better documented.

**Closed by aleksey-rowan** 2022-03-04 19:04 UTC
Labels: type.feature, area.create
